import { useEffect, useRef, useState } from "react";
import { PROTOCOL_VERSION, type DuetAction, type DuetClientCommand, type DuetCardId, type DuetRole, type PlayerId } from "@hangul-rummikub/shared";
import type { DuetWebSnapshot } from "../../lib/snapshot-wire-decoder.js";
import { getGameStartControl } from "../../lib/game-start.js";
import { createRequestId } from "../../lib/request-id.js";
import { DuetCommandRejected } from "../../lib/duet-command-error.js";
import { duetControls, duetClueError, DUET_ROLE_LABELS } from "./ui.js";

type Props=Readonly<{snapshot:DuetWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(command:DuetClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void}>;
type Game=NonNullable<DuetWebSnapshot['game']>;
function Emblem({kind='AGENT'}:{kind?:DuetRole}){
 return <svg className="duet-emblem" viewBox="0 0 64 64" aria-hidden="true">{kind==='ASSASSIN'?<><path d="M12 49 21 20 32 10 43 20 52 49 32 55Z" fill="currentColor"/><path d="m23 31 6 3m12-3-6 3M29 44h6" fill="none" stroke="var(--duet-paper)" strokeWidth="3"/></>:kind==='BYSTANDER'?<><circle cx="32" cy="22" r="10" fill="currentColor"/><path d="M12 53V46a20 20 0 0 1 40 0v7" fill="currentColor"/></>:<><path d="m18 24 5-13h18l5 13H18ZM10 28h44M23 30v7l9 8 9-8v-7M23 42 10 54h44L41 42 32 51Z" fill="currentColor" stroke="currentColor" strokeWidth="3"/><path d="m24 34 5 1m11-1-5 1" stroke="var(--duet-paper)" strokeWidth="2"/></>}</svg>;
}
export function DuetScreen(p:Props){
 const s=p.snapshot,start=getGameStartControl(s,p.pending||!p.connected);
 return <section className="duet-screen" aria-label="코드네임 듀엣">
  <header className="duet-header"><div className="duet-brand"><span className="duet-brand-mark"><Emblem/></span><div><span className="duet-kicker">CODENAMES</span><h1>DUET <span>코드네임 듀엣</span></h1></div></div><div className="duet-room"><span className={`duet-presence ${p.connected?'is-online':''}`} role="status">{p.connectionLabel}</span><span className="duet-room-code">ROOM / {s.room.roomCode}</span><button type="button" onClick={p.onCopy} disabled={p.pending}>초대 링크</button><button type="button" onClick={p.onLeave} disabled={p.pending}>나가기</button></div></header>
  {p.error&&<p className="duet-error" role="alert">{p.error}</p>}
  {!s.game?<>
   <section className="duet-lobby-hero"><div className="duet-lobby-copy"><span className="duet-kicker">OPERATION / MIDNIGHT</span><h2>단 하나의 힌트.<br/>우리 둘만의 작전.</h2><p>같은 단어, 서로 다른 비밀.<br/>당신의 한마디가 파트너의 길이 됩니다.</p><div className="duet-lobby-tags"><span>2인 협동</span><span>15명의 요원</span><span>9번의 기회</span></div></div><span className="duet-hero-caption">TRUST YOUR PARTNER. FIND YOUR WORDS.</span></section>
   <div className="duet-lobby-bottom"><section className="duet-seating"><span className="duet-kicker">YOUR OPERATIVES</span><h2>작전 파트너</h2><div className="duet-seats">{[0,1].map(i=>{const player=s.room.players[i];return <div className={`duet-seat ${player?'':'is-empty'}`} key={i}><span className="duet-avatar">{player?player.nickname.slice(0,1):'+'}</span><div><strong>{player?.nickname??'파트너를 기다리는 중'}</strong><span>{player?(player.connectionStatus==='CONNECTED'?'접속 중':'재접속 대기'):'초대 링크를 보내 함께 시작하세요'}</span></div><span className="duet-seat-id">0{i+1}</span></div>;})}</div><p>{start.guidance}</p><button type="button" className="duet-primary" disabled={!start.canStart} onClick={p.onStart}>작전 시작 <span aria-hidden="true">↗</span></button></section><div className="duet-intro"><span className="duet-kicker">MISSION BRIEFING</span><h2>서로를 믿고, 단어를 연결하세요.</h2>{[['01','비밀을 읽고','나만 보이는 요원을 묶어 한 단어와 숫자로 힌트를 줍니다.'],['02','단어를 찾아','파트너의 힌트로 단어를 추측합니다. 암살자를 고르면 둘 다 패배합니다.'],['03','함께 돌아오세요','번갈아 힌트를 주며 15명의 요원을 모두 찾으면 공동 승리!']].map(([n,title,body])=><div className="duet-intro-step" key={n}><span>{n}</span><div><strong>{title}</strong><p>{body}</p></div></div>)}</div></div>
  </>:<DuetTable key={s.game.gameId} game={s.game} {...p}/>}
  <details className="duet-rules"><summary>작전 매뉴얼 <span>게임 방법과 힌트 규칙</span></summary><div><p>자기 비밀 지도는 상대가 맞힐 정답입니다. 내 추측은 상대의 지도로 판정합니다. 먼저 준비한 사람이 첫 힌트를 주며 이후 번갈아 진행합니다.</p><p>힌트는 공백 없는 한 단어와 숫자 0–9입니다. 아직 보이는 보드 단어나 합성어 일부, 위치·글자 수로 힌트를 주지 마세요. 의미와 말장난의 허용 범위는 시작 전 두 사람이 합의하세요. 숫자0은 관련 단어를 피하라는 힌트입니다.</p><p>추측 수는 힌트 숫자로 제한되지 않습니다. 최소 한 번 추측한 뒤 그만둘 수 있고 토큰1개를 씁니다. 시민은 해당 추측자에게만 표시되며 턴이 끝납니다. 다른 사람은 그 단어를 선택할 수 있습니다.</p><p>토큰이 모두 없어지면 새 힌트 없이 최후의 추측을 합니다. 이때는 어느 쪽이든 추측할 수 있지만 시민도 즉시 패배입니다. 개인별 남은 정답 수는 말하지 마세요. 한쪽 지도의 요원을 모두 찾으면 완료 사실만 알려집니다.</p><p>‘이후 힌트 모두 넘기기’는 영구적인 선택입니다. 시간 제한은 없습니다. 연결이 끊겨도 같은 세션으로 돌아올 수 있으며, 나가기는 이번 작전을 취소합니다.</p></div></details>
 </section>;
}
function DuetTable({game:g,...p}:Props&{game:Game}){
 const self=p.snapshot.self.playerId,controls=duetControls(g,self),players=p.snapshot.room.players;
 const [map,setMap]=useState(controls.canClue),[selected,setSelected]=useState<DuetCardId|null>(null),[word,setWord]=useState(''),[number,setNumber]=useState(2);
 const [flight,setFlight]=useState(false),[message,setMessage]=useState<string|null>(null),[retry,setRetry]=useState<DuetClientCommand|null>(null),[passConfirm,setPassConfirm]=useState(false),[reviewPlayer,setReviewPlayer]=useState<PlayerId>(self);
 const lock=useRef(false),mounted=useRef(true),scope=`${g.gameId}:${g.gameRevision}`,scopeRef=useRef(scope);scopeRef.current=scope;
 const previousCards=useRef(g.cards);
 useEffect(()=>{previousCards.current=g.cards;},[g.cards]);
 const roleScope=g.phase==='FINISHED'?'FINISHED':`${g.phase}:${g.clueGiverId??'FIRST'}`;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{setSelected(null);setRetry(null);setMessage(null);setPassConfirm(false);},[scope]);
 useEffect(()=>{setMap(controls.canClue || g.phase==='GUESS' && g.clueGiverId===self);setWord('');},[roleScope,controls.canClue,self]);
 const busy=p.pending||!p.connected||flight||retry!==null,canGuess=controls.canGuess&&!busy&&!map;
 const nickname=(id:string)=>players.find(x=>x.playerId===id)?.nickname??'파트너';
 const partner=players.find(x=>x.playerId!==self),chosen=g.cards.find(c=>c.cardId===selected),clueError=duetClueError(word,g.cards);
 const key=g.phase==='FINISHED'?g.revealedKeys.find(k=>k.playerId===reviewPlayer)?.key??g.privateState.key:g.privateState.key;
 const last=g.history.at(-1),failedCard=g.phase==='FINISHED'&&(g.result.reason==='ASSASSIN'||g.result.reason==='SUDDEN_DEATH_MISS')&&last?.kind==='GUESS'?last.cardId:null;
 const previousFailure=useRef(failedCard);
 useEffect(()=>{previousFailure.current=failedCard;},[failedCard]);
 async function send(command:DuetClientCommand){
  if(lock.current||!p.connected)return;lock.current=true;setFlight(true);setMessage(null);const sentScope=scope;
  try{await p.onCommand(command);if(mounted.current&&scopeRef.current===sentScope){setRetry(null);setSelected(null);setWord('');}}
  catch(error){if(mounted.current&&scopeRef.current===sentScope){if(error instanceof DuetCommandRejected){setRetry(null);setMessage(error.message);}else{setRetry(command);setMessage('응답을 확인하지 못했습니다. 같은 요청의 결과를 다시 확인해주세요.');}}}
  finally{lock.current=false;if(mounted.current)setFlight(false);}
 }
 function act(payload:DuetAction){if(g.phase==='FINISHED'||busy)return;void send({kind:'duet:act',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload});}
 const phaseTitle=g.phase==='FINISHED'?'작전 종료':g.phase==='SUDDEN_DEATH'?'최후의 추측':controls.canClue?'당신이 힌트를 줄 차례':controls.canGuess?'당신이 단어를 찾을 차례':g.phase==='CLUE'?'파트너가 힌트를 생각하고 있어요':'파트너가 단어를 찾고 있어요';
 return <>
  <div className="duet-mission-bar"><div className="duet-partners"><span className="duet-avatar">{nickname(self).slice(0,1)}</span><span className="duet-link" aria-hidden="true">⌁</span><span className="duet-avatar duet-avatar-partner">{partner?.nickname.slice(0,1)}</span><div><strong>우리의 작전</strong><span>{nickname(self)} & {partner?.nickname}</span></div></div><div className="duet-found"><strong>{String(g.foundCount).padStart(2,'0')}<span> / 15</span></strong><span>접선한 요원</span></div><div className="duet-timer"><div><span className="duet-kicker">TURNS REMAINING</span><strong>남은 기회 {g.tokensRemaining}</strong></div><div className="duet-tokens" aria-label={`남은 턴 토큰 ${g.tokensRemaining}개`}>{Array.from({length:9},(_,i)=><span key={i} className={i<g.tokensRemaining?'':'is-spent'} aria-hidden="true">⌛</span>)}</div></div></div>
  {g.phase!=='FINISHED'&&g.currentClue&&<div className="duet-mobile-clue"><span>{g.phase==='CLUE'?'이전 힌트':g.phase==='SUDDEN_DEATH'?'마지막 힌트':'파트너와 나눈 힌트'}</span><strong>{g.currentClue.word}</strong><b>{g.currentClue.number}</b><span>{g.phase==='SUDDEN_DEATH'?'최후의 추측':controls.canGuess?'내가 추측 중':'파트너와 연결 중'}</span></div>}
  {partner?.connectionStatus!=='CONNECTED'&&<p className="duet-notice" role="status">파트너의 재접속을 기다리고 있습니다. 단어판과 비밀 지도는 그대로 보관됩니다.</p>}
  {g.phase==='FINISHED'&&<section className={`duet-result ${g.result.reason==='ALL_AGENTS'?'is-victory':''}`}><div><span className="duet-kicker">{g.result.reason==='ALL_AGENTS'?'MISSION ACCOMPLISHED':'MISSION DEBRIEF'}</span><h2>{g.result.reason==='ALL_AGENTS'?'완벽한 호흡. 작전 성공!':g.result.reason==='CANCELLED'?'이번 작전이 취소되었습니다':g.result.reason==='ASSASSIN'?'암살자와 마주쳤습니다':'마지막 단서가 엇갈렸습니다'}</h2><p>{g.result.reason==='ALL_AGENTS'?'15명의 요원 모두 무사히 접선했습니다.':`발견한 요원 ${g.foundCount}명. 양쪽 지도를 보며 단서를 함께 돌아보세요.`}</p></div>{players.some(x=>x.playerId===self&&x.isHost)?<button className="duet-primary" disabled={busy} onClick={p.onRematch}>새 작전 준비 ↗</button>:<p>방장이 새 작전을 준비할 수 있습니다.</p>}</section>}
  <div className="duet-table-layout"><section className={`duet-board-section ${map?'is-secret':''}`} aria-label="단어 보드"><div className="duet-board-toolbar"><div><span className="duet-kicker">{g.phase==='FINISHED'?'DECLASSIFIED':'OPERATION / MIDNIGHT'}</span><h2>{g.phase==='FINISHED'?`${nickname(reviewPlayer)}의 지도`:map?'나만의 비밀 지도':'공용 단어판'}</h2></div>{g.phase==='FINISHED'?<div className="duet-view-switch">{g.revealedKeys.map(k=><button key={k.playerId} type="button" aria-pressed={reviewPlayer===k.playerId} onClick={()=>setReviewPlayer(k.playerId)}>{nickname(k.playerId)}</button>)}</div>:<div className="duet-view-switch"><button type="button" aria-pressed={!map} onClick={()=>{setMap(false);setSelected(null);}}>단어판</button><button type="button" aria-pressed={map} onClick={()=>{setMap(true);setSelected(null);}}>비밀 지도</button></div>}</div>
   <div className="duet-map-caption">{g.phase==='FINISHED'?'두 사람의 비밀이 공개되었습니다.':map?'이 지도는 상대에게 줄 힌트입니다. 내 추측은 상대 지도에 따라 판정합니다.':'단어를 고른 뒤 확정하세요. 확정 전 선택은 나에게만 보입니다.'}</div>
   <div className="duet-board">{g.cards.map((card,i)=>{
    const role=key.find(k=>k.cardId===card.cardId)?.role??'BYSTANDER',showKey=map||g.phase==='FINISHED';
    const visual=card.foundBy!==null?'FOUND':failedCard===card.cardId?'FAILED':showKey?role:'HIDDEN';
    const failureRole=failedCard===card.cardId&&last?.kind==='GUESS'?last.outcome:null;
    const cover=card.foundBy!==null?'agent':failedCard===card.cardId&&last?.kind==='GUESS'&&last.outcome==='ASSASSIN'?'assassin':null;
    const arriving=cover==='agent'?previousCards.current.some(c=>c.cardId===card.cardId&&c.foundBy===null)&&previousCards.current!==g.cards:cover==='assassin'&&previousFailure.current!==failedCard;
    return <button className={`duet-word duet-word-${visual.toLowerCase()}${cover?' has-portrait':''}`} type="button" key={card.cardId} aria-pressed={selected===card.cardId} aria-label={`${card.word}${card.foundBy?' · 발견한 요원':failureRole?' · '+DUET_ROLE_LABELS[failureRole]:showKey?' · '+DUET_ROLE_LABELS[role]:''}${card.bystanderFor.includes(self)?' · 나에게 시민':''}`} disabled={!canGuess||card.foundBy!==null||card.bystanderFor.includes(self)} onClick={()=>setSelected(selected===card.cardId?null:card.cardId)}>
     {cover&&<span className={`duet-card-cover${arriving?' is-arriving':''}`} aria-hidden="true"><img src={`/images/word-duet/${cover}-contact.webp`} alt=""/><span className="duet-cover-shade"/></span>}
     <span className="duet-card-number" aria-hidden="true">{String(i+1).padStart(2,'0')}</span>{!cover&&(showKey||visual==='FAILED')&&<span className="duet-card-symbol"><Emblem kind={card.foundBy?'AGENT':visual==='FAILED'&&last?.kind==='GUESS'?last.outcome:role}/></span>}
     <strong>{card.word}</strong><span className="duet-card-bottom">{card.foundBy?<span className="duet-contact-stamp">CONTACTED · 접선 완료</span>:<>{(failureRole||showKey)&&<span>{DUET_ROLE_LABELS[failureRole??role]}</span>}{card.bystanderFor.map(id=><span className="duet-civilian-mark" key={id}>{id===self?'나':'상대'} · 시민</span>)}{!showKey&&!card.bystanderFor.length&&<span aria-hidden="true">◆</span>}</>}</span>
    </button>;
   })}</div>
   <div className="duet-board-legend"><span><i className="is-agent"/>요원</span><span><i className="is-civilian"/>시민</span><span><i className="is-assassin"/>암살자</span><span className="duet-board-signature">TWO MINDS. ONE MISSION.</span></div>
  </section>
  <aside className="duet-sidebar"><section className="duet-briefing"><span className="duet-kicker">FIELD NOTES</span><h2>{phaseTitle}</h2>
   {g.phase!=='FINISHED'&&g.phase==='CLUE'&&controls.canClue?<form onSubmit={e=>{e.preventDefault();if(!clueError)act({kind:'GIVE_CLUE',word:word.trim().normalize('NFC'),number});}}><p>녹색 요원들을 연결하는<br/>한 단어를 파트너에게 보내세요.</p><label htmlFor="duet-clue-word">힌트 한 단어</label><input id="duet-clue-word" value={word} onChange={e=>setWord(e.target.value)} maxLength={20} autoComplete="off" placeholder="예: 우주" disabled={busy}/><div className="duet-clue-number"><label htmlFor="duet-clue-number">연결한 단어 수</label><select id="duet-clue-number" value={number} onChange={e=>setNumber(Number(e.target.value))} disabled={busy}>{Array.from({length:10},(_,i)=><option key={i} value={i}>{i}{i===0?' · 피할 단어':''}</option>)}</select></div>{word&&clueError&&<p className="duet-form-error" role="alert">{clueError}</p>}<button className="duet-primary" type="submit" disabled={busy||clueError!==null}>{flight?'전달 중…':'힌트 보내기 ↗'}</button></form>:<>{g.currentClue&&<div className="duet-clue-ticket"><span>{nickname(g.currentClue.playerId)}의 {g.phase==='CLUE'?'이전 ':''}힌트</span><div><strong>{g.currentClue.word}</strong><b>{g.currentClue.number}</b></div><span>한 단어에 담긴 우리의 암호</span></div>}{g.phase==='CLUE'&&!controls.canClue&&<p>파트너가 단어를 연결하고 있습니다.<br/>잠시 기다려주세요.</p>}{g.phase==='GUESS'&&!controls.canGuess&&<p>파트너의 추측을 기다려주세요.<br/>선택을 유도하는 반응은 잠시 비밀로.</p>}</>}
   {g.phase==='SUDDEN_DEATH'&&<p className="duet-sudden">새 힌트 없이, 마지막 추측.<br/>시민을 골라도 작전은 끝납니다.</p>}
   {g.playerStates.filter(x=>x.cluesComplete||x.passed).map(x=><p className="duet-complete-note" key={x.playerId}>{nickname(x.playerId)} · {x.cluesComplete?'힌트를 줄 요원 모두 발견':'이후 힌트 제공을 넘김'}</p>)}
   {g.phase!=='FINISHED'&&controls.canClue&&<details className="duet-pass"><summary>이후 힌트 모두 넘기기</summary><p>이번 작전이 끝날 때까지 파트너만 힌트를 줍니다.</p><label><input type="checkbox" checked={passConfirm} onChange={e=>setPassConfirm(e.target.checked)} disabled={busy}/> 되돌릴 수 없는 선택임을 확인합니다</label><button type="button" disabled={busy||!passConfirm} onClick={()=>act({kind:'PASS_CLUES'})}>이후 힌트 넘기기</button></details>}
  </section>
  <section className="duet-log"><div className="duet-log-heading"><h3>작전 기록</h3><span>{g.history.length?`${g.history.length}개의 기록`:'첫 단서를 기다리며'}</span></div><ol>{[...g.history].reverse().map((h,i)=><li key={g.history.length-i}><span className={`duet-log-dot ${h.kind==='GUESS'?h.outcome.toLowerCase():''}`}/><div>{h.kind==='CLUE'?<><strong>{h.word} <b>{h.number}</b></strong><span>{nickname(h.playerId)}의 힌트</span></>:h.kind==='GUESS'?<><strong>{g.cards.find(c=>c.cardId===h.cardId)?.word} <small>{DUET_ROLE_LABELS[h.outcome]}</small></strong><span>{nickname(h.playerId)}의 추측</span></>:<><strong>{h.kind==='END'?'이번 추측 종료':'이후 힌트 넘김'}</strong><span>{nickname(h.playerId)}</span></>}</div></li>)}</ol>{!g.history.length&&<p>첫 힌트가 우리의 작전을 시작합니다.</p>}</section></aside></div>
  {g.phase!=='FINISHED'&&controls.canGuess&&<footer className="duet-action-bar"><div aria-live="polite"><span className="duet-kicker">YOUR NEXT MOVE</span><strong>{map?'비밀 지도를 보고 있습니다':chosen?`「${chosen.word}」을 선택했습니다`:'어떤 단어가 떠오르나요?'}</strong><span>{map?'단어판으로 돌아가면 추측할 수 있습니다.':'확정한 단어는 되돌릴 수 없습니다.'}</span></div><div className="duet-action-buttons">{map?<button className="duet-primary" type="button" onClick={()=>setMap(false)}>단어판으로 돌아가기</button>:<button className="duet-primary" type="button" disabled={!chosen||busy} onClick={()=>chosen&&act({kind:'GUESS',cardId:chosen.cardId})}>{flight?'확인 중…':chosen?`${chosen.word} 확정`:'단어 선택 후 확정'}</button>}{g.phase==='GUESS'&&<button type="button" disabled={!controls.canEnd||busy} onClick={()=>act({kind:'END_GUESSES'})}>이번 추측 마치기</button>}</div></footer>}
  {(message||retry)&&<div className="duet-error" role="alert"><p>{message}</p>{retry&&<button type="button" disabled={flight||!p.connected} onClick={()=>void send(retry)}>같은 요청 결과 재확인</button>}</div>}
 </>;
}
