import { useEffect, useRef, useState } from "react";
import { PROTOCOL_VERSION, guryongtuParity, type GuryongtuClientCommand, type GuryongtuParity, type GuryongtuProjection, type TileId } from "@hangul-rummikub/shared";
import type { GuryongtuWebSnapshot } from "../../lib/snapshot-wire-decoder.js";
import { createRequestId } from "../../lib/request-id.js";
import { getGameStartControl } from "../../lib/game-start.js";
import { GuryongtuCommandRejected } from "../../lib/guryongtu-command-error.js";
import { guryongtuInstruction, guryongtuScope, guryongtuSelection } from "./ui.js";

type Props = Readonly<{snapshot: GuryongtuWebSnapshot; connected: boolean; pending: boolean; error: string | null; connectionLabel: string; onCommand(command: GuryongtuClientCommand): Promise<void>; onRematch(): void; onStart(): void; onLeave(): void; onCopy(): void}>;
function Crest() { return <svg viewBox="0 0 100 100" fill="none" aria-hidden="true"><circle cx="50" cy="50" r="39" stroke="currentColor" strokeWidth="1"/><path d="M50 11C24 24 23 47 50 50s27 26 0 39M50 11c26 13 27 36 0 39s-27 26 0 39" stroke="currentColor" strokeWidth="2"/><circle cx="50" cy="30" r="5" fill="currentColor"/><circle cx="50" cy="70" r="5" fill="currentColor"/><path d="m10 50 7-4v8Zm80 0-7-4v8Z" fill="currentColor"/></svg>; }
function TileFace({rank, parity, empty = false}: {rank?: number | undefined; parity?: GuryongtuParity | undefined; empty?: boolean}) {
  return <span className={`gt-face ${empty ? "gt-face-empty" : (parity ?? (rank ? guryongtuParity(rank) : "ODD")) === "ODD" ? "gt-face-light" : "gt-face-dark"}`}>
    {empty ? <span className="gt-tile-symbol">◇</span> : <><span className="gt-tile-corner" aria-hidden="true">九</span>{rank === undefined ? <span className="gt-tile-crest"><Crest/></span> : <span className="gt-tile-rank">{rank}</span>}<span className="gt-tile-parity">{(parity ?? (rank ? guryongtuParity(rank) : "ODD")) === "ODD" ? "홀수" : "짝수"}</span></>}
  </span>;
}
export function GuryongtuScreen(props: Props) {
  const s = props.snapshot, start = getGameStartControl(s, props.pending || !props.connected);
  return <section className="guryongtu-screen" aria-label="구룡투">
    <header className="gt-header"><div className="gt-brand"><div className="gt-brand-mark"><Crest/></div><div><span className="gt-eyebrow">NINE TILES · TWO MINDS</span><h1>구룡투 <span>九龍鬪</span></h1></div></div><div className="gt-room-tools"><span className="gt-room-code">방 {s.room.roomCode}</span><span className="gt-connection" role="status">{props.connectionLabel}</span><button type="button" disabled={props.pending} onClick={props.onCopy}>초대 링크</button><button type="button" disabled={props.pending} onClick={props.onLeave}>나가기</button></div></header>
    {props.error && <div className="gt-error" role="alert">{props.error}</div>}
    {s.game === null ? <div className="gt-lobby"><span className="gt-eyebrow">두 사람의 대결장</span><h2>아홉 개의 수,<br/>마지막까지 숨겨둔 한 수.</h2><div className="gt-lobby-tiles" aria-hidden="true"><TileFace rank={1}/><TileFace rank={8}/><TileFace rank={9}/></div><p>상대의 홀짝을 보고, 숨겨진 숫자를 읽어보세요.<br/>큰 수가 이깁니다. 단, 1은 9를 이깁니다.</p><div className="gt-seats">{s.room.players.map(p => <div className="gt-seat" key={p.playerId}><span className="gt-avatar">{p.nickname.slice(0, 1)}</span><strong>{p.nickname}</strong><span>{p.connectionStatus === "CONNECTED" ? "접속 중" : "재접속 대기"}{p.isHost ? " · 방장" : ""}</span></div>)}{s.room.players.length === 1 && <div className="gt-seat gt-seat-empty"><span className="gt-avatar">＋</span><strong>상대를 기다립니다</strong><button type="button" onClick={props.onCopy}>초대 링크 복사</button></div>}</div><p className="gt-guidance">{start.guidance}</p><button type="button" className="gt-primary" disabled={!start.canStart} onClick={props.onStart}>대결 시작 <span aria-hidden="true">↗</span></button><span className="gt-lobby-meta">2인 전용 · 2승 선취 · 시간 제한 없음</span></div> : <GuryongtuTable key={s.game.gameId} {...props} game={s.game}/>}
    <details className="gt-help"><summary>게임 방법 <span>숫자는 숨기고, 승패로 추리합니다</span></summary><div><p>각자 1부터 9까지의 타일을 한 장씩 받습니다. 흰색은 홀수, 검은색은 짝수입니다. 공격자가 먼저 내면 수비자가 홀짝을 보고 응수합니다.</p><p>높은 숫자가 이깁니다. 단, 1은 9를 이기고 같은 숫자는 무승부입니다. 쓴 타일은 다시 사용할 수 없으며 상대 숫자는 끝까지 공개하지 않습니다.</p><p>승자가 다음 공격자가 됩니다. 무승부면 공격자는 그대로입니다. 최대 9번 겨뤄 승수가 많은 사람이 한 판을 가져갑니다. 남은 대결로 따라잡을 수 없으면 먼저 정산합니다.</p><p>두 판을 먼저 이기면 최종 승리입니다. 한 판이 동률이면 매치 승수를 유지하고 타일을 새로 받아 다시 겨룹니다. 다음 판의 첫 공격자는 무작위로 정합니다.</p><p>시간 제한이 없으며 연결이 끊겨도 같은 자리로 돌아올 수 있습니다. 나가기 버튼을 누르면 이번 매치가 취소됩니다.</p></div></details>
  </section>;
}
function GuryongtuTable({game: g, ...props}: Props & {game: GuryongtuProjection}) {
  const selfId = props.snapshot.self.playerId, scope = guryongtuScope(g);
  const [selection, setSelection] = useState<{scope: string; tileId: TileId} | null>(null);
  const [flight, setFlight] = useState(false), [message, setMessage] = useState<string | null>(null), [retry, setRetry] = useState<GuryongtuClientCommand | null>(null);
  const pendingRef = useRef<GuryongtuClientCommand | null>(null), mounted = useRef(true), scopeRef = useRef(scope);
  scopeRef.current = scope;
  useEffect(() => {mounted.current = true; return () => {mounted.current = false;};}, []);
  useEffect(() => {setSelection(null); setRetry(null); setMessage(null);}, [scope]);
  const me = g.playerStates.find(p => p.playerId === selfId)!, opponent = g.playerStates.find(p => p.playerId !== selfId)!;
  const nickname = (id: string) => props.snapshot.room.players.find(p => p.playerId === id)?.nickname ?? "플레이어";
  const opponentOnline = props.snapshot.room.players.find(p => p.playerId === opponent.playerId)?.connectionStatus === "CONNECTED";
  const selected = guryongtuSelection(g, selfId, selection?.scope === scope ? selection.tileId : null);
  const canAct = g.phase === "PLAYING" && g.activePlayerId === selfId && props.connected && !props.pending && !flight && retry === null;
  const last = g.history.at(-1), lastRound = g.roundResults.at(-1);
  const showPrevious = g.submitted === null && selected === null && last !== undefined;
  const ownTile = g.privateState.submitted ?? selected ?? (showPrevious ? g.privateState.used.at(-1) : undefined);
  const otherPlay = g.submitted?.playerId === opponent.playerId ? g.submitted : showPrevious ? last?.plays.find(p => p.playerId === opponent.playerId) : undefined;
  const resultLabel = last ? `${last.duel}번째 대결 · ${last.winnerPlayerId === null ? "무승부" : last.winnerPlayerId === selfId ? "승리" : "패배"}` : "";
  async function send(command: GuryongtuClientCommand) {
    if (pendingRef.current || !props.connected || props.pending) return;
    pendingRef.current = command; setFlight(true); setMessage(null); const sentScope = scope;
    try { await props.onCommand(command); if (mounted.current && scopeRef.current === sentScope) {setRetry(null); setSelection(null);} }
    catch (error) { if (mounted.current && scopeRef.current === sentScope) { if (error instanceof GuryongtuCommandRejected) {setRetry(null); setMessage(error.message);} else {setRetry(command); setMessage("응답을 확인하지 못했습니다. 같은 요청의 결과를 다시 확인해주세요.");} } }
    finally { if (pendingRef.current === command) pendingRef.current = null; if (mounted.current) setFlight(false); }
  }
  function submit() {
    if (!canAct || !selected || g.phase !== "PLAYING") return;
    void send({kind: "guryongtu:act", protocolVersion: PROTOCOL_VERSION, requestId: createRequestId(), gameId: g.gameId, expectedGameRevision: g.gameRevision, turnId: g.turnId, payload: {kind: "PLAY_TILE", tileId: selected.tileId}});
  }
  function nextRound() { if (g.phase !== "ROUND_RESULT" || g.confirmedPlayerIds.includes(selfId)) return; void send({kind: "guryongtu:nextRound", protocolVersion: PROTOCOL_VERSION, requestId: createRequestId(), gameId: g.gameId, expectedGameRevision: g.gameRevision, roundId: g.roundId, payload: {}}); }
  return <>
    <div className="gt-match-strip"><span className="gt-match-caption">MATCH <strong>{g.round}</strong></span><span>두 판을 먼저 이기면 승리</span><span className="gt-match-badges"><span>나 {"◆".repeat(me.matchWins)}{"◇".repeat(2 - me.matchWins)}</span><i>·</i><span>상대 {"◆".repeat(opponent.matchWins)}{"◇".repeat(2 - opponent.matchWins)}</span></span></div>
    <div className="gt-table-layout"><main className="gt-play-surface">
      <div className="gt-player-row"><div className="gt-player"><span className="gt-avatar">{nickname(opponent.playerId).slice(0, 1)}</span><div><strong>{nickname(opponent.playerId)}</strong><span>{opponentOnline ? "상대" : "재접속 대기"} · {g.attackerId === opponent.playerId ? "공격" : "수비"}</span></div></div><div className="gt-reserve" aria-label={`상대 남은 타일: 홀수 ${opponent.oddCount}개, 짝수 ${opponent.evenCount}개`}><span><i className="gt-dot-light"/>홀수 {opponent.oddCount}</span><span><i className="gt-dot-dark"/>짝수 {opponent.evenCount}</span></div></div>
      <section className="gt-arena" aria-label="대결장"><div className="gt-arena-ring" aria-hidden="true"/><div className="gt-arena-heading"><span className="gt-eyebrow">{showPrevious ? `${last?.duel}번째 대결` : `${Math.min(9, g.history.length + 1)}번째 대결`}</span><div className="gt-round-lamps" aria-label={`이번 판: 나 ${me.wins}승, 상대 ${opponent.wins}승`}>{Array.from({length: 9}, (_, i) => <span key={i} className={g.history[i] ? g.history[i]!.winnerPlayerId === null ? "gt-lamp-draw" : g.history[i]!.winnerPlayerId === selfId ? "gt-lamp-win" : "gt-lamp-loss" : ""} title={g.history[i] ? `${i + 1}번째: ${g.history[i]!.winnerPlayerId === null ? "무승부" : g.history[i]!.winnerPlayerId === selfId ? "내 승리" : "상대 승리"}` : `${i + 1}번째 대결 대기`}>{i + 1}</span>)}</div></div>
      <div className="gt-duel"><div className="gt-duel-slot"><span>상대의 수</span><TileFace parity={otherPlay?.parity} empty={!otherPlay}/><small>{otherPlay ? "숫자 비공개" : "아직 내지 않았습니다"}</small></div><div className="gt-versus"><span>{opponent.wins}</span><i>:</i><span>{me.wins}</span><small>이번 판 승수</small></div><div className="gt-duel-slot"><span>나의 수</span><TileFace rank={ownTile?.rank} empty={!ownTile}/><small>{g.privateState.submitted ? "제출 완료" : selected ? "확정 전 · 변경 가능" : showPrevious ? "내가 사용한 타일" : "타일을 골라주세요"}</small></div></div>
      <div className="gt-result-line" aria-live="polite" key={`${g.roundId}:${g.history.length}`}><span className={last?.winnerPlayerId === selfId ? "gt-result-win" : ""}>{resultLabel || "아직 읽히지 않은 아홉 개의 수"}</span>{last && <small>상대의 숫자는 공개되지 않습니다</small>}</div>
      </section>
      {g.phase === "PLAYING" ? <div className={`gt-turn-message ${canAct ? "gt-is-my-turn" : ""}`} role="status"><span className="gt-turn-dot"/><strong>{guryongtuInstruction(g, selfId)}</strong>{!opponentOnline && <span>상대의 연결을 기다리고 있습니다.</span>}</div> : <div className="gt-round-result" role="status"><span className="gt-eyebrow">{g.phase === "FINISHED" ? "MATCH RESULT" : "ROUND RESULT"}</span><h2>{g.phase === "FINISHED" ? g.result.reason === "CANCELLED" ? "매치가 취소되었습니다" : `${nickname(g.result.winnerPlayerIds[0]!)} 최종 승리` : lastRound?.winnerPlayerId ? `${nickname(lastRound.winnerPlayerId)} · 한 판 승리` : "무승부 · 다시 겨룹니다"}</h2><p>{g.phase === "FINISHED" ? g.result.reason === "CANCELLED" ? "방장이 대기실로 돌아가 새 대결을 열 수 있습니다." : "아홉 개의 수로 완성한 멋진 승부였습니다." : lastRound?.winnerPlayerId ? "매치 승수에 한 승이 더해졌습니다." : "매치 승수는 그대로, 타일은 새롭게 받습니다."}</p>{g.phase === "ROUND_RESULT" ? <button type="button" className="gt-primary" disabled={!props.connected || props.pending || flight || retry !== null || g.confirmedPlayerIds.includes(selfId)} onClick={nextRound}>{g.confirmedPlayerIds.includes(selfId) ? "상대의 확인을 기다립니다" : "확인하고 다음 판"}</button> : props.snapshot.room.players.find(p => p.playerId === selfId)?.isHost ? <button type="button" className="gt-primary" disabled={!props.connected || props.pending} onClick={props.onRematch}>대기실에서 다시 하기</button> : <p>방장이 다음 게임을 선택할 수 있습니다.</p>}</div>}
      <section className="gt-hand-section" aria-label="내 타일"><div className="gt-hand-heading"><div><span className="gt-eyebrow">YOUR TILES</span><h2>내 타일 <span>{me.handCount} / 9</span></h2></div><span className="gt-private-note">나에게만 보이는 숫자</span></div><div className="gt-hand">{[...g.privateState.hand].sort((a, b) => a.rank - b.rank).map(tile => <button key={tile.tileId} type="button" disabled={!canAct} aria-pressed={selected?.tileId === tile.tileId} aria-label={`${tile.rank}번 ${tile.rank % 2 ? "홀수" : "짝수"} 타일`} onClick={() => setSelection(selected?.tileId === tile.tileId ? null : {scope, tileId: tile.tileId})}><TileFace rank={tile.rank}/><span className="gt-selection-mark" aria-hidden="true">{selected?.tileId === tile.tileId ? "✓" : "·"}</span></button>)}{!me.handCount && <p className="gt-no-tiles">이번 판의 타일을 모두 사용했습니다.</p>}</div>
      {g.phase === "PLAYING" && <div className="gt-submit-bar"><div><span>{selected ? `${selected.rank}번 · ${selected.rank % 2 ? "홀수" : "짝수"} 선택` : g.privateState.submitted ? "타일 제출 완료" : "타일을 선택해주세요"}</span><small>{selected ? "확정한 타일은 되돌릴 수 없습니다" : "큰 수가 승리 · 1은 9를 이깁니다"}</small></div><button type="button" className="gt-primary" disabled={!canAct || !selected} onClick={submit}>{flight ? "결과 확인 중…" : "이 타일로 확정"}<span aria-hidden="true">↗</span></button></div>}
      </section>
      {(message || retry) && <div className="gt-error" role="alert"><p>{message}</p>{retry && <button type="button" disabled={!props.connected || flight} onClick={() => void send(retry)}>같은 요청 결과 재확인</button>}</div>}
    </main><aside className="gt-history-panel" aria-label="대결 기록"><div className="gt-history-title"><span className="gt-eyebrow">THE STORY SO FAR</span><h2>대결 기록</h2></div><div className="gt-history-legend"><span>상대</span><span>나</span><span>결과</span></div>{g.history.length ? <ol>{g.history.map((h, i) => {const other = h.plays.find(p => p.playerId === opponent.playerId)!;return <li key={h.duel}><span className="gt-history-index">{String(h.duel).padStart(2, "0")}</span><span className={`gt-mini-tile ${other.parity === "ODD" ? "gt-mini-light" : "gt-mini-dark"}`}>{other.parity === "ODD" ? "홀" : "짝"}</span><span className={`gt-mini-tile ${g.privateState.used[i]!.rank % 2 ? "gt-mini-light" : "gt-mini-dark"}`}>{g.privateState.used[i]!.rank}</span><span className={h.winnerPlayerId === selfId ? "gt-history-win" : ""}>{h.winnerPlayerId === null ? "무" : h.winnerPlayerId === selfId ? "승" : "패"}</span></li>;})}</ol> : <div className="gt-history-empty"><Crest/><p>첫 대결을 기다립니다</p><span>홀짝과 승패가<br/>다음 수의 단서가 됩니다.</span></div>}<div className="gt-history-foot"><span className="gt-rule-one">1 <span>↗</span> 9</span><p>가장 작은 수가<br/>가장 큰 수를 이깁니다.</p></div>{g.roundResults.length > 0 && <details className="gt-match-history"><summary>지난 판 승부</summary>{g.roundResults.map(r => <p key={r.round}>{r.round}판 · {r.winnerPlayerId ? `${nickname(r.winnerPlayerId)} 승리` : "동률 재경기"}</p>)}</details>}</aside></div>
  </>;
}
