import { useEffect, useRef, useState } from "react";
import { PROTOCOL_VERSION, JAIPUR_GOODS, type JaipurCard, type JaipurCardType, type JaipurClientCommand, type PlatformPlayerViewV2 } from "@hangul-rummikub/shared";
import type { JaipurWebSnapshot } from "../../lib/snapshot-wire-decoder.js";
import { createRequestId } from "../../lib/request-id.js";
import { getGameStartControl } from "../../lib/game-start.js";
import { JaipurCommandRejected } from "../../lib/jaipur-command-error.js";
import { emptyJaipurDraft, previewJaipur, JAIPUR_LABELS, type JaipurMode } from "./ui.js";

type Props=Readonly<{snapshot:JaipurWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(command:JaipurClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void}>;
type Game=NonNullable<JaipurWebSnapshot['game']>;
const MODES:ReadonlyArray<{mode:JaipurMode;title:string;hint:string}>=[{mode:'TAKE_GOOD',title:'상품 1장',hint:'시장에서 상품 한 장을 가져오세요.'},{mode:'EXCHANGE',title:'교환',hint:'받을 시장 상품과 내놓을 손패·낙타를 고르세요.'},{mode:'TAKE_CAMELS',title:'낙타 전부',hint:'시장의 낙타를 모두 내 무리로 데려옵니다.'},{mode:'SELL',title:'판매',hint:'손패에서 같은 상품을 골라 판매하세요.'}];
export function JaipurArt({type}:{type:JaipurCardType}) {
  return <svg viewBox="0 0 100 90" className={`jp-art jp-art-${type.toLowerCase()}`} aria-hidden="true">
    {type==='DIAMOND'?<><path d="M18 32 32 15H68L82 32 50 77Z" fill="currentColor"/><path d="m18 32 32 45 32-45H18m14-17 18 62 18-62M18 32h64M32 15 43 32h14l11-17" fill="none" stroke="#fff" strokeOpacity=".5" strokeWidth="2"/></>:null}
    {type==='GOLD'?<><path d="m17 56 7-20h52l8 20-10 14H26Z" fill="currentColor"/><path d="M24 36h52l-9 15H33ZM17 56h67M33 51l-7 19m41-19 7 19" stroke="#fff" strokeOpacity=".5" fill="none" strokeWidth="2"/></>:null}
    {type==='SILVER'?<><ellipse cx="50" cy="60" rx="30" ry="10" fill="currentColor"/><path d="M20 43v17q30 20 60 0V43" fill="currentColor"/><ellipse cx="50" cy="43" rx="30" ry="11" fill="currentColor" stroke="#fff" strokeOpacity=".65" strokeWidth="2"/><path d="M24 53q26 15 52 0" stroke="#fff" strokeOpacity=".5" fill="none"/></>:null}
    {type==='CLOTH'?<><path d="M22 20q24-9 56 0v50q-26-10-56 0Z" fill="currentColor"/><path d="M31 18v49m12-51v50m13-50v50m13-47v50M23 36q26-8 54 0M23 53q26-8 54 0" fill="none" stroke="#fff" strokeOpacity=".35" strokeWidth="2"/></>:null}
    {type==='SPICE'?<><path d="M29 20q21 8 42 0l-7 20q22 28 2 35H34Q14 68 36 40Z" fill="currentColor"/><path d="M35 40h30M40 50q16 5 10 20" stroke="#fff" strokeOpacity=".5" fill="none" strokeWidth="3"/><path d="m47 15 8-8 4 10" stroke="currentColor" fill="none" strokeWidth="3"/></>:null}
    {type==='LEATHER'?<><path d="M32 14q18 10 36 0l15 19q-21 8-6 28L64 76q-14-9-28 0L22 61q14-20-6-28Z" fill="currentColor"/><path d="M32 28q18 7 35 0l-4 34q-13-4-26 0Z" stroke="#fff" strokeOpacity=".4" fill="none" strokeWidth="2" strokeDasharray="3 3"/></>:null}
    {type==='CAMEL'?<><path d="M15 55q-5-12 8-14 5-24 19-9 11-20 22 0l6 6 6-21q5-8 13-2l-2 9-7 2-4 30-9 3-2 21h-7l-1-20H35l-4 20h-7l1-24Z" fill="currentColor"/><path d="m15 47-7 9m68-19 9-3" stroke="currentColor" strokeWidth="4" fill="none"/><circle cx="85" cy="18" r="1.8" fill="#48351b"/></>:null}
  </svg>;
}
function Card({card,selected,disabled,onClick}:{card:JaipurCard;selected:boolean;disabled:boolean;onClick():void}) {
  return <button className={`jp-card jp-card-${card.type.toLowerCase()}`} type="button" aria-pressed={selected} disabled={disabled} onClick={onClick} aria-label={`${JAIPUR_LABELS[card.type]}${selected?' 선택됨':''}`}><span className="jp-card-corner">{JAIPUR_LABELS[card.type]}</span><JaipurArt type={card.type}/><strong>{JAIPUR_LABELS[card.type]}</strong><span className="jp-card-mark" aria-hidden="true">{selected?'✓':'◆'}</span></button>;
}
export function JaipurScreen(props:Props) {
  const {snapshot:s}=props,start=getGameStartControl(s,props.pending||!props.connected);
  return <section className="jaipur-screen" aria-label="자이푸르">
    <header className="jp-header"><div><span className="jp-eyebrow">THE MERCHANTS' MARKET</span><h1>JAIPUR <span>자이푸르</span></h1></div><div className="jp-room-info"><strong>방 {s.room.roomCode}</strong><span role="status">{props.connectionLabel}</span><button type="button" disabled={props.pending} onClick={props.onCopy}>초대 링크</button><button type="button" disabled={props.pending} onClick={props.onLeave}>나가기</button></div></header>
    {props.error&&<p role="alert" className="jp-error">{props.error}</p>}
    <details className="jp-help"><summary>게임 방법 · 시장에서 상품을 모으고, 팔고, 인장 2개를 먼저 얻으세요</summary><div><p>차례마다 상품 1장 가져오기, 상품 교환, 시장 낙타 전부 가져오기, 같은 상품 판매 중 하나를 합니다. 손패는 7장까지이며 낙타는 손패 수에 포함되지 않습니다.</p><p>교환은 상품 2장 이상부터 같은 수량으로 합니다. 같은 상품을 받고 내놓을 수 없습니다. 다이아몬드·금·은은 최소 2장 판매해야 합니다. 3·4·5장 이상 판매에는 보너스가 있습니다.</p><p>상품 토큰 3종이 소진되거나 시장을 채울 카드가 부족하면 정산합니다. 낙타가 더 많으면 5점, 점수 동률은 보너스 토큰 수 → 상품 토큰 수로 비교합니다. 모두 같으면 인장 없이 다음 라운드를 진행합니다.</p><p>시간 제한은 없습니다. 상대 손패·낙타 수·현재 점수는 비공개입니다. 연결이 끊겨도 같은 자리로 돌아올 수 있고, 나가기 버튼은 매치를 취소합니다.</p></div></details>
    {s.game===null?<div className="jp-lobby"><div className="jp-lobby-art"><JaipurArt type="CAMEL"/></div><span className="jp-eyebrow">A TABLE FOR TWO</span><h2>두 상인의 시장이 열립니다</h2><p>상품을 모아 제때 판매하고, 교환에 낙타를 활용하세요.</p><div className="jp-seats">{s.room.players.map(p=><div key={p.playerId}><span className="jp-avatar">{p.nickname.slice(0,1)}</span><strong>{p.nickname}</strong><span>{p.isHost?'방장 · ':''}{p.connectionStatus==='CONNECTED'?'접속 중':'재접속 대기'}</span></div>)}</div><p>{start.guidance}</p><button className="jp-primary" disabled={!start.canStart} onClick={props.onStart}>자이푸르 시작</button><p className="jp-muted">정확히 2인 · 인장 2개 선승 · 시간 제한 없음</p></div>:<JaipurTable key={s.game.gameId} game={s.game} selfId={s.self.playerId} players={s.room.players} {...props}/>}
  </section>;
}
function JaipurTable({game:g,selfId,players,...props}:Props&{game:Game;selfId:string;players:readonly PlatformPlayerViewV2[]}) {
  const [draft,setDraft]=useState(()=>emptyJaipurDraft());
  const [flight,setFlight]=useState(false),[message,setMessage]=useState<string|null>(null),[retry,setRetry]=useState<JaipurClientCommand|null>(null);
  const commandRef=useRef<JaipurClientCommand|null>(null),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return ()=>{mounted.current=false;};},[]);
  const scope=`${g.gameId}:${g.roundId}:${g.phase}:${g.phase==='PLAYING'?g.turnId:''}`;
  const scopeRef=useRef(scope);scopeRef.current=scope;
  useEffect(()=>{setDraft(emptyJaipurDraft());setMessage(null);setRetry(null);commandRef.current=null;},[scope]);
  const canAct=g.phase==='PLAYING'&&g.activePlayerId===selfId&&props.connected&&!props.pending&&!flight&&retry===null;
  const preview=g.phase!=='FINISHED'?previewJaipur(g,draft):null;
  const nickname=(id:string)=>players.find(p=>p.playerId===id)?.nickname??'상인';
  const me=g.playerStates.find(p=>p.playerId===selfId)!,opponent=g.playerStates.find(p=>p.playerId!==selfId)!;
  const opponentOnline=players.find(p=>p.playerId===opponent.playerId)?.connectionStatus==='CONNECTED';
  const hand=[...g.privateState.hand].sort((a,b)=>[...JAIPUR_GOODS,'CAMEL'].indexOf(a.type)-[...JAIPUR_GOODS,'CAMEL'].indexOf(b.type));
  async function send(c:JaipurClientCommand) {
    if(commandRef.current!==null||!props.connected)return;
    commandRef.current=c;setFlight(true);setMessage(null);const sentScope=scope;
    try {await props.onCommand(c);if(mounted.current&&scopeRef.current===sentScope){setRetry(null);setDraft(emptyJaipurDraft());}}
    catch(error){if(mounted.current&&scopeRef.current===sentScope){if(error instanceof JaipurCommandRejected){setRetry(null);setMessage(error.message);}else{setRetry(c);setMessage('응답을 확인하지 못했습니다. 같은 요청의 결과를 다시 확인해주세요.');}}}
    finally{if(mounted.current){commandRef.current=null;setFlight(false);}}
  }
  function choose(card:JaipurCard,area:'market'|'hand') {
    if(!canAct)return;
    setMessage(null);
    setDraft(d=>{const key=area==='market'?'marketIds':'handIds',selected=d[key];if(selected.includes(card.cardId))return {...d,[key]:selected.filter(id=>id!==card.cardId)};
      if(area==='market'&&d.mode==='TAKE_GOOD')return {...d,marketIds:[card.cardId]};
      if(area==='hand'&&d.mode==='SELL'&&g.privateState.hand.some(c=>selected.includes(c.cardId)&&c.type!==card.type))return {...d,handIds:[card.cardId]};
      return {...d,[key]:[...selected,card.cardId]};});
  }
  function submit(){if(g.phase!=='PLAYING'||!preview?.action||!canAct)return;void send({kind:'jaipur:act',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload:preview.action});}
  const description=(cards:JaipurCard[])=>{const groups=new Map<JaipurCardType,number>();cards.forEach(c=>groups.set(c.type,(groups.get(c.type)??0)+1));return [...groups].map(([type,n])=>`${JAIPUR_LABELS[type]} ${n}`).join(' · ')||'선택 없음';};
  const received=draft.mode==='TAKE_CAMELS'?`낙타 ${g.market.filter(c=>c.type==='CAMEL').length}`:description(g.market.filter(c=>draft.marketIds.includes(c.cardId)));
  const offered=description(g.privateState.hand.filter(c=>draft.handIds.includes(c.cardId)))+(draft.mode==='EXCHANGE'&&draft.camelCount?` + 낙타 ${draft.camelCount}`:'');
  const last=g.roundResults.at(-1);
  return <>
    <div className="jp-player-strip"><div className="jp-player"><span className="jp-avatar">{nickname(opponent.playerId).slice(0,1)}</span><div><strong>{nickname(opponent.playerId)}</strong><span>손패 {opponent.handCount}장 · 낙타 비공개{opponentOnline?'':' · 재접속 대기'}</span></div></div><div className="jp-seal-score"><span>내 인장 <b>{me.seals}</b></span><i aria-hidden="true">◆</i><span>상대 <b>{opponent.seals}</b></span></div><div className="jp-turn"><strong>{g.phase==='PLAYING'?(g.activePlayerId===selfId?'내 차례':`${nickname(g.activePlayerId)} 차례`):g.phase==='ROUND_RESULT'?'라운드 정산':'매치 종료'}</strong><span>{g.round}라운드 · 시간 제한 없음</span></div></div>
    {g.phase!=='PLAYING'?<section className="jp-result" aria-label="라운드 결과"><span className="jp-eyebrow">{g.phase==='FINISHED'?'MATCH RESULT':'ROUND RESULT'}</span><h2>{g.phase==='FINISHED'?(g.result.reason==='CANCELLED'?'매치가 취소되었습니다':`${nickname(g.result.winnerPlayerIds[0]!)} 승리!`):last?.winnerPlayerId?`${nickname(last.winnerPlayerId)} · 인장 획득`:'동률 · 인장 없이 다음 라운드'}</h2>{last&&<><p>{last.reason==='DECK_DEPLETED'?'시장을 채울 카드가 부족합니다.':'상품 토큰 3종이 소진되었습니다.'}</p><div className="jp-score-table"><table><thead><tr><th>상인</th><th>상품</th><th>보너스</th><th>낙타</th><th>합계</th></tr></thead><tbody>{last.scores.map(s=><tr key={s.playerId}><th>{nickname(s.playerId)}</th><td>{s.goodsPoints}</td><td>{s.bonusPoints}</td><td>{s.camelPoints}<small> {s.camelCount}마리</small></td><td><strong>{s.total}</strong></td></tr>)}</tbody></table></div></>}{g.phase==='ROUND_RESULT'?<><p>{g.confirmedPlayerIds.map(nickname).join(', ')}{g.confirmedPlayerIds.length?' · 확인 완료':'두 상인이 확인하면 다음 라운드를 시작합니다.'}</p><button className="jp-primary" disabled={!props.connected||props.pending||flight||retry!==null||g.confirmedPlayerIds.includes(g.privateState.playerId)} onClick={()=>void send({kind:'jaipur:nextRound',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,roundId:g.roundId,payload:{}})}>{g.confirmedPlayerIds.includes(g.privateState.playerId)?'상대 확인 기다리는 중':'확인 · 다음 라운드'}</button></>:players.find(p=>p.playerId===selfId)?.isHost?<button className="jp-primary" disabled={props.pending||!props.connected} onClick={props.onRematch}>같은 방에서 다시 하기</button>:<p>방장이 다음 게임을 선택할 수 있습니다.</p>}</section>:null}
    <div className="jp-table-layout"><section className="jp-market-section"><div className="jp-section-heading"><h2>공용 시장</h2><span>덱 {g.deckCount}장 · 버림패 {g.discardTop?JAIPUR_LABELS[g.discardTop.type]:'없음'}</span></div><div className="jp-market">{g.market.map(card=><Card key={card.cardId} card={card} selected={draft.mode==='TAKE_CAMELS'?card.type==='CAMEL':draft.marketIds.includes(card.cardId)} disabled={!canAct||draft.mode==='SELL'||draft.mode==='TAKE_CAMELS'||card.type==='CAMEL'} onClick={()=>choose(card,'market')}/>)}</div>{g.phase==='PLAYING'&&<><div className="jp-modes" aria-label="행동 선택">{MODES.map(m=><button key={m.mode} type="button" aria-pressed={draft.mode===m.mode} disabled={!canAct} onClick={()=>{setDraft(emptyJaipurDraft(m.mode));setMessage(null);}}>{m.title}</button>)}</div><p className="jp-hint">{canAct?MODES.find(m=>m.mode===draft.mode)?.hint:'상대의 차례가 끝나면 행동할 수 있습니다.'}</p></>}{g.feedback&&<p className="jp-feedback" role="status">{nickname(g.feedback.playerId)} · {g.feedback.kind==='SELL'?`상품 ${g.feedback.count}장 판매`:g.feedback.kind==='EXCHANGE'?`상품 ${g.feedback.count}장 교환`:g.feedback.kind==='TAKE_CAMELS'?`낙타 ${g.feedback.count}마리 획득`:'상품 1장 획득'}</p>}</section>
    <aside className="jp-token-bank"><div className="jp-section-heading"><h2>상품 토큰</h2><span>{g.goodsBank.filter(b=>b.values.length===0).length} / 3종 소진</span></div>{g.goodsBank.map(b=><div className={`jp-token-row jp-color-${b.type.toLowerCase()}`} key={b.type}><span>{JAIPUR_LABELS[b.type]}</span><div aria-label={`${JAIPUR_LABELS[b.type]} 남은 토큰 ${b.values.join(', ')||'없음'}`}>{b.values.length?b.values.map((n,i)=><span className="jp-token" key={i}>{n}</span>):<span className="jp-muted">소진</span>}</div></div>)}<div className="jp-bonuses">{g.bonusBank.map(b=><div key={b.size}><span>{b.size}{b.size===5?'+':''}</span><strong>{b.count}개 남음</strong></div>)}</div><p className="jp-muted">보너스 값은 뽑은 뒤 나에게만 공개</p></aside></div>
    <section className="jp-hand-section"><div className="jp-section-heading"><h2>내 손패 <span>{hand.length} / 7장</span></h2><span>나에게만 보입니다</span></div><div className="jp-hand-and-herd"><div className="jp-hand">{hand.map(card=><Card key={card.cardId} card={card} selected={draft.handIds.includes(card.cardId)} disabled={!canAct||(draft.mode!=='SELL'&&draft.mode!=='EXCHANGE')} onClick={()=>choose(card,'hand')}/>)}{!hand.length&&<p className="jp-empty">손패가 없습니다. 시장에서 상품을 가져오세요.</p>}</div><div className="jp-herd"><JaipurArt type="CAMEL"/><strong>내 낙타 {g.privateState.camelCount}마리</strong>{g.phase==='PLAYING'&&draft.mode==='EXCHANGE'&&<div className="jp-stepper"><button type="button" aria-label="교환 낙타 줄이기" disabled={!canAct||draft.camelCount===0} onClick={()=>setDraft(d=>({...d,camelCount:d.camelCount-1}))}>−</button><span aria-live="polite">{draft.camelCount}</span><button type="button" aria-label="교환 낙타 늘리기" disabled={!canAct||draft.camelCount>=g.privateState.camelCount} onClick={()=>setDraft(d=>({...d,camelCount:d.camelCount+1}))}>+</button><small>교환에 사용</small></div>}</div></div><details className="jp-my-tokens"><summary>내 획득 토큰 · {g.privateState.goodsTokens.reduce((n,t)=>n+t.value,0)+g.privateState.bonusTokens.reduce((n,t)=>n+t.value,0)}점</summary><p>상품 {g.privateState.goodsTokens.map(t=>`${JAIPUR_LABELS[t.type]} ${t.value}`).join(' · ')||'없음'}</p><p>보너스 {g.privateState.bonusTokens.map(t=>`${t.size}장 판매 ${t.value}점`).join(' · ')||'없음'}</p><p>낙타 우세 5점은 라운드가 끝날 때 결정됩니다.</p></details></section>
    {g.phase==='PLAYING'&&<footer className="jp-draft-bar"><div className="jp-draft-preview" aria-live="polite"><div><span>{draft.mode==='SELL'?'판매할 상품':'받을 카드'}</span><strong>{draft.mode==='SELL'?offered:received}</strong></div>{draft.mode==='EXCHANGE'&&<><span aria-hidden="true">⇄</span><div><span>내놓을 카드</span><strong>{offered}</strong></div></>}<div><span>처리 후 손패</span><strong>{preview?.handAfter} / 7장</strong></div>{draft.mode==='SELL'&&preview?.action&&<div><span>예상 획득</span><strong>상품 {preview.goodsPoints}점{preview.bonusSize&&g.bonusBank.some(b=>b.size===preview.bonusSize&&b.count>0)?` + ${preview.bonusSize}장 보너스`:''}</strong></div>}</div><button type="button" className="jp-primary" disabled={!canAct||!preview?.action} onClick={submit}>{flight?'결과 확인 중…':draft.mode==='SELL'?'판매 확정':draft.mode==='EXCHANGE'?'교환 확정':'가져오기 확정'}</button><p className={preview?.reason?'jp-validation':'jp-muted'}>{preview?.reason||'선택한 행동을 확인한 뒤 확정하세요.'}</p></footer>}
    {(message||retry)&&<div className="jp-error" role="alert"><p>{message}</p>{retry&&<button type="button" disabled={!props.connected||flight} onClick={()=>void send(retry)}>같은 요청 결과 재확인</button>}</div>}
    {g.roundResults.length>1&&<details className="jp-history"><summary>지난 라운드 결과</summary>{g.roundResults.map(r=><p key={r.round}>{r.round}라운드 · {r.scores.map(s=>`${nickname(s.playerId)} ${s.total}점`).join(' / ')} · {r.winnerPlayerId?`${nickname(r.winnerPlayerId)} 인장`:'무승부'}</p>)}</details>}
  </>;
}
