import { useEffect,useRef,useState,type CSSProperties,type ReactNode } from 'react';
import { PROTOCOL_VERSION,SABOTEUR_TOOLS,type SaboteurAction,type SaboteurCard,type SaboteurClientCommand,type SaboteurProjection,type SaboteurTool,type PlatformPlayerViewV2 } from '@hangul-rummikub/shared';
import type { SaboteurWebSnapshot } from '../../lib/snapshot-wire-decoder.js';
import { getGameStartControl } from '../../lib/game-start.js';
import { createRequestId } from '../../lib/request-id.js';
import { SaboteurCommandRejected } from '../../lib/saboteur-command-error.js';
import { Atlas,PathArt,CardArt,ToolArt,TOOL_NAMES,cardLabel } from './art.js';
import { saboteurBoardBounds,saboteurCandidates,saboteurFeedback } from './ui.js';
type Props={snapshot:SaboteurWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(command:SaboteurClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void};
function Dialog({children,onClose,label}:{children:ReactNode;onClose():void;label:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="sab-dialog" aria-label={label} onCancel={onClose}><button className="sab-dialog-close" onClick={onClose} autoFocus aria-label="닫기">×</button>{children}</dialog>;}
function Rules(){return <><span className="sab-eyebrow">HOW TO PLAY</span><h2>금까지 이어지는 길.<br/>믿을 수 없는 동료.</h2><ol><li>광부는 출발점에서 금까지 길을 잇고, 사보타지는 이를 막습니다. 역할은 나만 봅니다.</li><li>내 차례에는 카드 1장을 사용하거나 버립니다. 덱이 남아 있으면 자동으로 1장 보충합니다.</li><li>길을 놓거나, 장비를 고장 내거나 수리하고, 낙석으로 길을 지우거나 지도로 목표를 엿볼 수 있습니다.</li><li>장비가 하나라도 고장 나면 길을 놓을 수 없습니다. 수리·지도 등 행동과 버리기는 가능합니다.</li><li>금에 도달하면 광부 승리. 덱과 전원 손패가 소진되면 사보타지 승리입니다.</li><li>매 라운드 역할을 공개하고 금을 분배합니다. 광부는 차례대로 금 카드를 직접 고릅니다. 3라운드 후 금 합계로 최종 승자를 정합니다.</li></ol><p>시간이 끝나면 손패 한 장을 무작위로 버리거나 금을 자동 선택합니다. 라운드 결과는 전원 확인하면 즉시, 그렇지 않으면 1분 후 다음 라운드로 넘어갑니다.</p><p>길은 180°만 회전하며 옆 카드와 맞고 출발점에서 이어져야 합니다. 두 장비 수리 카드도 고장 하나만 수리합니다.</p><p className="sab-muted">행동·금 선택 30초 · 결과 확인 최대 1분 · 새로고침 후 복원 · 명시적으로 나가면 경기 취소</p></>;}
export function SaboteurScreen(props:Props){
 const s=props.snapshot,[help,setHelp]=useState(false),start=getGameStartControl(s,props.pending||!props.connected);
 return <section className="sab-screen" aria-label="사보타지"><header className="sab-header"><div><span className="sab-eyebrow">A GAME OF PATHS & HIDDEN INTENTIONS</span><h1>SABOTEUR <span>사보타지</span></h1></div><div className="sab-room"><span>방 <b>{s.room.roomCode}</b></span><span className="sab-connection" role="status">{props.connectionLabel}</span><button onClick={()=>setHelp(true)}>게임 방법</button><button onClick={props.onCopy}>초대</button><button onClick={props.onLeave} disabled={props.pending}>나가기</button></div></header>
 {props.error&&<p className="sab-error" role="alert">{props.error}</p>}
 {s.game===null?<div className="sab-lobby"><div className="sab-lobby-art"><Atlas panel="MINER"/><Atlas panel="SABOTEUR"/><span className="sab-lobby-seal">누구의 편인가요?</span></div><div className="sab-lobby-copy"><span className="sab-eyebrow">THE MINE IS WAITING</span><h2>함께 파고들수록<br/>의심은 깊어진다.</h2><p>길을 이어 금을 찾아내세요.<br/>하지만 모두가 금을 원하는 건 아닙니다.</p><div className="sab-lobby-facts"><span>3–10명</span><span>3라운드</span><span>비밀 역할</span></div><div className="sab-lobby-roster">{s.room.players.map(p=><span key={p.playerId}><i>{p.nickname.slice(0,1)}</i>{p.nickname}{p.isHost?' · 방장':''}<small>{p.connectionStatus==='CONNECTED'?'접속':'재접속 대기'}</small></span>)}</div><button className="sab-primary sab-start" onClick={props.onStart} disabled={!start.canStart}>{props.pending?'준비 중…':'광산으로 입장'}</button>{!start.canStart&&<p className="sab-muted">{s.room.players.length<3?'3명 이상 모이면 방장이 시작할 수 있습니다.':!s.room.players.find(p=>p.playerId===s.self.playerId)?.isHost?'방장이 시작하면 역할을 받습니다.':'모든 참가자의 연결을 확인해주세요.'}</p>}</div></div>:<Table key={s.game.gameId} game={s.game} players={s.room.players} {...props}/>}
 {help&&<Dialog onClose={()=>setHelp(false)} label="사보타지 게임 방법"><Rules/></Dialog>}</section>;
}
function Table({game:g,players,...props}:Props&{game:SaboteurProjection;players:readonly PlatformPlayerViewV2[]}){
 const [selected,setSelected]=useState<SaboteurCard['cardId']|null>(null),[rotation,setRotation]=useState<0|180>(0),[action,setAction]=useState<SaboteurAction|null>(null),[tool,setTool]=useState<SaboteurTool>('PICKAXE');
 const [flight,setFlight]=useState(false),[retry,setRetry]=useState<SaboteurClientCommand|null>(null),[message,setMessage]=useState<string|null>(null),[privatePanel,setPrivatePanel]=useState<'role'|'notes'|null>(null),[chat,setChat]=useState('');
 const [now,setNow]=useState<number>(props.snapshot.serverTime);
 useEffect(()=>{const base=performance.now();setNow(props.snapshot.serverTime);const timer=window.setInterval(()=>setNow(props.snapshot.serverTime+performance.now()-base),100);return()=>window.clearInterval(timer);},[props.snapshot.serverTime]);
 const seconds=g.deadlineAt===null?null:Math.max(0,Math.ceil((g.deadlineAt-now)/1000));
 const chatMessages=useRef<HTMLDivElement>(null),chatVersion=JSON.stringify(g.messages);
 useEffect(()=>{const el=chatMessages.current;if(el)el.scrollTop=el.scrollHeight;},[g.roundId,chatVersion]);
 const lock=useRef(false),alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const turn='turnId' in g?g.turnId:g.phase;useEffect(()=>{setSelected(null);setRotation(0);setAction(null);},[turn,g.roundId]);
 const card=g.privateState.hand.find(c=>c.cardId===selected)??null,me=g.playerStates.find(p=>p.playerId===g.privateState.playerId)!,name=(id:string)=>players.find(p=>p.playerId===id)?.nickname??'광부';
 const available=props.connected&&!props.pending&&!flight&&!retry&&(seconds===null||seconds>0),canAct=available&&g.phase==='PLAYING'&&g.activePlayerId===me.playerId;
 const candidates=canAct?saboteurCandidates(g,card,rotation):[];
 async function send(command:SaboteurClientCommand){if(lock.current||!props.connected)return;lock.current=true;setFlight(true);setMessage(null);try{await props.onCommand(command);if(alive.current){setRetry(null);if(command.kind==='saboteur:say')setChat('');else {setAction(null);setSelected(null);}if(command.kind==='saboteur:act'&&command.payload.kind==='MAP')setPrivatePanel('notes');}}
 catch(error){if(alive.current){setMessage(error instanceof Error?error.message:'요청을 확인하지 못했습니다.');setRetry(error instanceof SaboteurCommandRejected?null:command);}}finally{lock.current=false;if(alive.current)setFlight(false);}}
 function submit(a:SaboteurAction){if(!('turnId' in g)||!available)return;void send({kind:'saboteur:act',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload:a});}
 function choose(c:SaboteurCard){setSelected(c.cardId);setAction(null);setRotation(0);setMessage(null);if(c.kind==='REPAIR')setTool(c.tools[0]!);}
 function selectPlayer(id:typeof me.playerId){if(!card||!canAct)return;if(card.kind==='BREAK')setAction({kind:'BREAK',cardId:card.cardId,targetPlayerId:id});if(card.kind==='REPAIR')setAction({kind:'REPAIR',cardId:card.cardId,targetPlayerId:id,tool});}
 const status=g.phase==='PLAYING'?(g.activePlayerId===me.playerId?'내 차례입니다':`${name(g.activePlayerId)}님의 차례`):g.phase==='GOLD_SELECTION'?`${name(g.activePlayerId)}님이 금을 고르는 중`:g.phase==='ROUND_RESULT'?'다음 라운드를 준비하세요':'경기 종료';
 const feedback=saboteurFeedback(g,name),gold=g.privateState.gold.reduce((n,c)=>n+c.value,0);
 let hint=!canAct?'다른 참가자의 행동을 살펴보세요.':!card?'손패에서 사용할 카드를 선택하세요.':card.kind==='PATH'?(me.brokenTools.length?'장비를 수리해야 길을 놓을 수 있습니다. 카드 버리기도 가능합니다.':candidates.length?'빛나는 칸을 눌러 길을 미리 놓으세요.':'이 방향으로 놓을 수 있는 곳이 없습니다. 회전하거나 버릴 수 있습니다.'):card.kind==='BREAK'?'위 참가자 중 방해할 사람을 선택하세요.':card.kind==='REPAIR'?'수리할 장비와 참가자를 선택하세요.':card.kind==='MAP'?'뒷면 목표 카드 A·B·C 중 하나를 선택하세요.':'보드에서 제거할 길 카드를 선택하세요.';
 if(action)hint=action.kind==='DISCARD'?'선택한 카드 한 장을 비공개로 버립니다.':action.kind==='PLACE'?`선택한 칸에 ${rotation}° 방향으로 길을 놓습니다.`:action.kind==='BREAK'?`${name(action.targetPlayerId)}님의 장비를 고장 냅니다.`:action.kind==='REPAIR'?`${name(action.targetPlayerId)}님의 ${TOOL_NAMES[action.tool]}을 수리합니다.`:action.kind==='MAP'?`목표 ${action.goalId}를 나만 확인합니다.`:'선택한 길을 낙석으로 제거합니다.';
 return <><div className="sab-turn-banner"><span className="sab-round-token">{g.round}<small>/ 3 ROUND</small></span><strong aria-live="polite">{status}</strong>{seconds!==null&&<span className={`sab-timer ${seconds<=10?'sab-timer-urgent':''}`} role="timer" aria-label={g.phase==='ROUND_RESULT'?'다음 라운드까지 남은 시간':'행동 남은 시간'}><span>{g.phase==='ROUND_RESULT'?'다음 라운드':g.phase==='GOLD_SELECTION'?'금 선택':'행동 제한'}</span><b>{seconds}초</b></span>}<span className="sab-countdown-announcement" aria-live="assertive" aria-atomic="true">{seconds!==null&&seconds<=5?(seconds===0?'시간 종료. 서버에서 다음 단계로 진행합니다.':`${seconds}초 남았습니다.`):''}</span><span className="sab-deck-summary">덱 <b>{g.deckCount}</b>장 · 버림 {g.discardCount}장</span></div>
 <div className="sab-players">{g.playerStates.map((p,i)=>{const eligible=canAct&&card&&(card.kind==='BREAK'?p.playerId!==me.playerId&&!p.brokenTools.includes(card.tool):card.kind==='REPAIR'?p.brokenTools.includes(tool):false),active='activePlayerId' in g&&g.activePlayerId===p.playerId;
 return <button className={`sab-player ${active?'sab-player-active':''} ${eligible?'sab-player-target':''}`} key={p.playerId} disabled={!eligible} aria-pressed={!!action&&'targetPlayerId' in action&&action.targetPlayerId===p.playerId} onClick={()=>selectPlayer(p.playerId)}><span className="sab-avatar">{String(i+1).padStart(2,'0')}</span><span className="sab-player-name">{name(p.playerId)}{p.playerId===me.playerId?<small>나</small>:null}<span className="sab-player-hand">손패 {p.handCount}장{players.find(x=>x.playerId===p.playerId)?.connectionStatus!=='CONNECTED'?' · 연결 대기':''}</span></span><span className="sab-equipment">{SABOTEUR_TOOLS.map(t=><ToolArt key={t} tool={t} broken={p.brokenTools.includes(t)}/>)}</span></button>;})}</div>
 <div className="sab-play-layout"><div className="sab-main-table"><Board game={g} selected={card} rotation={rotation} candidates={candidates} action={action} canAct={canAct} onAction={setAction}/>{feedback&&<p className="sab-feedback" aria-live="polite">{feedback}</p>}
 {g.phase==='GOLD_SELECTION'||g.phase==='ROUND_RESULT'||g.phase==='FINISHED'?<Results game={g} name={name} enabled={available} onGold={id=>submit({kind:'TAKE_GOLD',cardId:id})} onConfirm={()=>{if(g.phase==='ROUND_RESULT')void send({kind:'saboteur:nextRound',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,roundId:g.roundId,payload:{}});}} onRematch={props.onRematch} isHost={!!players.find(p=>p.playerId===me.playerId)?.isHost}/>:null}
 </div><aside className="sab-sidebar"><section className="sab-private"><span className="sab-eyebrow">ONLY YOU CAN SEE</span><h2>나의 비밀</h2><button className="sab-role-back" onClick={()=>setPrivatePanel('role')}><span className="sab-role-sigil">?</span><span>역할 확인</span></button><div className="sab-private-bottom"><span>내 금 <b>{gold}</b></span><button onClick={()=>setPrivatePanel('notes')}>지도 기록 {g.privateState.observations.length}</button></div></section>
 <section className="sab-chat"><h2>광산의 대화 <span>모두에게 공개</span></h2><div ref={chatMessages} className="sab-chat-messages" role="log" aria-live="polite" aria-label="공개 대화">{!g.messages.length?<p className="sab-muted">“어느 길로 갈까요?”<br/>누구의 말을 믿을지 선택하세요.</p>:g.messages.map((m,i)=><p key={`${g.roundId}-${i}`}><b>{name(m.playerId)}</b><span>{m.text}</span></p>)}</div><form onSubmit={e=>{e.preventDefault();if(!available||!chat.trim()||g.phase==='FINISHED')return;void send({kind:'saboteur:say',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,roundId:g.roundId,payload:{text:chat.trim(),sequence:g.privateState.chatSequence}});}}><input aria-label="공개 메시지" placeholder="모두에게 한마디…" maxLength={240} value={chat} onChange={e=>setChat(e.target.value)} disabled={!available||g.phase==='FINISHED'}/><button disabled={!available||!chat.trim()||g.phase==='FINISHED'} aria-label="메시지 보내기">↑</button></form></section></aside></div>
 {g.phase==='PLAYING'&&<section className="sab-hand-dock"><div className="sab-hand-title"><h2>내 손패 <small>{me.handCount}장</small></h2><span>나만 볼 수 있습니다</span><button onClick={()=>setPrivatePanel('role')}>내 역할</button></div><div className="sab-hand">{g.privateState.hand.map((c,i)=><button draggable={canAct} onDragStart={e=>{choose(c);e.dataTransfer.setData('text/plain',c.cardId);e.dataTransfer.effectAllowed='move';}} type="button" key={c.cardId} className="sab-hand-card" style={{'--fan':`${(i-(me.handCount-1)/2)*1.6}deg`} as CSSProperties} disabled={!canAct} aria-label={cardLabel(c)} aria-pressed={selected===c.cardId} onClick={()=>choose(c)}><CardArt card={c} rotation={selected===c.cardId?rotation:0}/><span className="sab-hand-label">{cardLabel(c)}</span></button>)}</div>
 <div className="sab-action-bar"><div><span className="sab-eyebrow">{!card?'01 · 카드 선택':!action?'02 · 대상 선택':'03 · 사용 확정'}</span><p aria-live="polite">{flight?'서버에서 결과를 확인하는 중…':hint}</p>{card?.kind==='REPAIR'&&card.tools.length===2&&<div className="sab-tool-choices">{card.tools.map(t=><button key={t} aria-pressed={tool===t} disabled={!canAct} onClick={()=>{setTool(t);setAction(null);}}>{TOOL_NAMES[t]} 수리</button>)}</div>}</div><div className="sab-controls"><button disabled={!canAct||card?.kind!=='PATH'} onClick={()=>{setRotation(r=>r===0?180:0);setAction(null);}}>↻ 180°</button><button disabled={!canAct||!card} aria-pressed={action?.kind==='DISCARD'} onClick={()=>{if(card)setAction({kind:'DISCARD',cardId:card.cardId});}}>카드 버리기</button><button className="sab-primary" disabled={!canAct||!action} onClick={()=>{if(action)submit(action);}}>사용 확정</button></div></div></section>}
 {(message||retry)&&<div className="sab-error" role="alert">{message}{retry&&<button disabled={!props.connected||flight} onClick={()=>void send(retry)}>같은 요청 결과 재확인</button>}</div>}
 {privatePanel&&<Dialog onClose={()=>setPrivatePanel(null)} label={privatePanel==='role'?'내 비밀 역할':'나만 보는 지도 기록'}>{privatePanel==='role'?<><div className="sab-secret-portrait"><Atlas panel={g.privateState.role}/></div><span className="sab-eyebrow">YOUR SECRET ROLE</span><h2>{g.privateState.role==='MINER'?'당신은 광부입니다.':'당신은 사보타지입니다.'}</h2><p>{g.privateState.role==='MINER'?'출발점과 금을 연결하세요. 동료들 사이에 방해꾼이 숨어 있습니다.':'광부들이 금에 닿지 못하게 하세요. 의도를 들키지 않는 것이 중요합니다.'}</p><p className="sab-muted">다른 사람의 역할은 라운드가 끝나면 공개됩니다.</p></>:<><span className="sab-eyebrow">PRIVATE MAP NOTES</span><h2>나만 아는 목표</h2>{g.privateState.observations.length?g.privateState.observations.map(o=><div className="sab-note" key={o.goalId}><b>목표 {o.goalId}</b><span>{o.face==='GOLD'?'금이 있습니다.':'돌입니다.'}</span></div>):<p>지도를 사용하면 확인한 정보가 여기에 남습니다.</p>}<p className="sab-muted">이 기록은 나에게만 보이며, 이번 라운드 동안 유지됩니다.</p></>}</Dialog>}</>;
}
function Board({game:g,selected:c,rotation,candidates,action,canAct,onAction}:{game:SaboteurProjection;selected:SaboteurCard|null;rotation:0|180;candidates:{x:number;y:number}[];action:SaboteurAction|null;canAct:boolean;onAction(a:SaboteurAction):void}){
 const viewport=useRef<HTMLDivElement>(null),[zoom,setZoom]=useState(.7),bounds=saboteurBoardBounds(g),width=(bounds.maxX-bounds.minX+1)*82,height=(bounds.maxY-bounds.minY+1)*110;
 const pan=useRef<{x:number;y:number;left:number;top:number}|null>(null),overview=useRef(false);
 function fit(){const el=viewport.current;if(!el)return;overview.current=true;setZoom(Math.max(.15,Math.min(1,Math.min((el.clientWidth-32)/width,(el.clientHeight-32)/height))));el.scrollTo({left:0,top:0});}
 useEffect(()=>{overview.current=false;setZoom(.7);const frame=requestAnimationFrame(()=>{const el=viewport.current;if(el&&el.clientWidth<600){fit();return;}if(el)el.scrollTo({left:Math.max(0,-bounds.minX*82*.7-32),top:Math.max(0,-bounds.minY*110*.7-el.clientHeight/2+55*.7)});});return()=>cancelAnimationFrame(frame);},[g.roundId]);
 useEffect(()=>{const el=viewport.current;if(!el)return;const observer=new ResizeObserver(()=>{if(overview.current)fit();});observer.observe(el);if(overview.current)fit();return()=>observer.disconnect();},[g.roundId,width,height]);
 useEffect(()=>{const el=viewport.current;if(!el||!c)return;overview.current=false;const next=Math.max(.7,zoom);setZoom(next);const target=c.kind==='MAP'?{x:8,y:0}:g.board.at(-1)??{x:0,y:0};const frame=requestAnimationFrame(()=>el.scrollTo({left:Math.max(0,(target.x-bounds.minX)*82*next-el.clientWidth/2+41*next),top:Math.max(0,(target.y-bounds.minY)*110*next-el.clientHeight/2+55*next)}));return()=>cancelAnimationFrame(frame);},[c?.cardId]);
 const pos=(x:number,y:number):CSSProperties=>({left:(x-bounds.minX)*82,top:(y-bounds.minY)*110});
 function latest(){const p=g.feedback?.position,el=viewport.current;if(p&&el)el.scrollTo({left:(p.x-bounds.minX)*82*zoom-el.clientWidth/2+41*zoom,top:(p.y-bounds.minY)*110*zoom-el.clientHeight/2+55*zoom,behavior:'smooth'});}
 return <section className="sab-board-wrap" aria-label="공용 광산 보드"><div className="sab-board-toolbar"><span><i/>공용 광산</span><div><button onClick={()=>{overview.current=false;setZoom(z=>Math.max(.15,z-.15));}} aria-label="보드 축소">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>{overview.current=false;setZoom(z=>Math.min(1.8,z+.15));}} aria-label="보드 확대">+</button><button onClick={fit}>전체 보기</button><button onClick={latest} disabled={!g.feedback?.position}>최근 행동</button></div></div>
 <div className="sab-board-viewport" ref={viewport} onPointerDown={e=>{if(e.target instanceof Element&&e.target.closest('button'))return;pan.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!pan.current||e.pointerType==='touch')return;e.currentTarget.scrollLeft=pan.current.left-(e.clientX-pan.current.x);e.currentTarget.scrollTop=pan.current.top-(e.clientY-pan.current.y);}} onPointerUp={()=>{pan.current=null;}} onPointerCancel={()=>{pan.current=null;}}>
 <div className="sab-board-space" style={{width:width*zoom,height:height*zoom}}><div className="sab-board" style={{width,height,transform:`scale(${zoom})`}}><div className="sab-board-card sab-start-card" style={pos(0,0)}><PathArt path="NESW" start/><span className="sab-board-tag">출발</span></div>
 {g.goals.map(goal=><button className={`sab-board-card sab-goal ${goal.face===null?'sab-goal-hidden':''}`} style={pos(goal.x,goal.y)} key={goal.goalId} aria-label={`목표 ${goal.goalId}${goal.face===null?' 미공개':goal.face==='GOLD'?' 금':' 돌'}`} disabled={!canAct||c?.kind!=='MAP'||goal.face!==null} aria-pressed={action?.kind==='MAP'&&action.goalId===goal.goalId} onClick={()=>{if(c?.kind==='MAP')onAction({kind:'MAP',cardId:c.cardId,goalId:goal.goalId});}}>{goal.face===null?<><span className="sab-goal-ornament">✦</span><strong>?</strong></>:goal.face==='GOLD'?<Atlas panel="GOLD"/>:<PathArt path={goal.face==='ROCK_NE'?'ES':'WS'} rotation={goal.rotation}/>}<span className="sab-board-tag">목표 {goal.goalId}</span></button>)}
 {g.board.map(tile=><button className={`sab-board-card ${g.feedback?.kind==='PLACE'&&g.feedback.position?.x===tile.x&&g.feedback.position.y===tile.y?'sab-recent-card':''}`} style={pos(tile.x,tile.y)} key={tile.cardId} disabled={!canAct||c?.kind!=='ROCKFALL'} aria-label={`길 ${tile.x}, ${tile.y}${c?.kind==='ROCKFALL'?' 제거 선택':''}`} aria-pressed={action?.kind==='ROCKFALL'&&action.x===tile.x&&action.y===tile.y} onClick={()=>{if(c?.kind==='ROCKFALL')onAction({kind:'ROCKFALL',cardId:c.cardId,x:tile.x,y:tile.y});}}><PathArt path={tile.path} rotation={tile.rotation}/></button>)}
 {candidates.map(p=><button key={`${p.x},${p.y}`} className="sab-placement" style={pos(p.x,p.y)} aria-label={`길 놓기 ${p.x}, ${p.y}`} aria-pressed={action?.kind==='PLACE'&&action.x===p.x&&action.y===p.y} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move';}} onDrop={e=>{e.preventDefault();if(c?.kind==='PATH'&&e.dataTransfer.getData('text/plain')===c.cardId)onAction({kind:'PLACE',cardId:c.cardId,x:p.x,y:p.y,rotation});}} onClick={()=>{if(c?.kind==='PATH')onAction({kind:'PLACE',cardId:c.cardId,x:p.x,y:p.y,rotation});}}>{action?.kind==='PLACE'&&action.x===p.x&&action.y===p.y&&c?.kind==='PATH'?<PathArt path={c.path} rotation={rotation}/>:<span>+</span>}</button>)}
 </div></div></div><p className="sab-board-caption">보드를 밀어서 탐색 · 카드를 선택하면 사용할 곳이 표시됩니다</p></section>;
}
function Results({game:g,name,enabled,onGold,onConfirm,onRematch,isHost}:{game:SaboteurProjection;name:(id:string)=>string;enabled:boolean;onGold(id:SaboteurCard['cardId']):void;onConfirm():void;onRematch():void;isHost:boolean}){
 if(g.phase==='PLAYING')return null;const result=g.roundResults.at(-1),cancelled=g.phase==='FINISHED'&&g.result.reason==='CANCELLED';
 return <section className="sab-result"><span className="sab-eyebrow">{g.phase==='FINISHED'?'THE FINAL REVEAL':'ROUND COMPLETE'}</span><h2>{cancelled?'경기가 취소되었습니다.':g.phase==='FINISHED'?`${g.result.winnerPlayerIds.map(name).join(' · ')} ${g.result.winnerPlayerIds.length>1?'공동 ':''}승리!`:result?.winner==='MINERS'?'광부들이 금을 찾았습니다!':result?.winner==='SABOTEURS'?'사보타지가 광산을 막았습니다!':'금에 도달하지 못했습니다.'}</h2>
 {result&&!cancelled&&<div className="sab-role-reveal">{result.roles.map(p=><div key={p.playerId}><Atlas panel={p.role}/><strong>{name(p.playerId)}</strong><small>{p.role==='MINER'?'광부':'사보타지'}</small></div>)}</div>}
 {g.phase==='GOLD_SELECTION'&&(g.activePlayerId===g.privateState.playerId?<><p>금 카드 한 장을 고르세요. 남은 카드는 다음 광부에게 전달됩니다.</p><div className="sab-gold-choices">{g.privateState.goldChoices.map(c=><button key={c.cardId} disabled={!enabled} aria-label={`${c.value}금 선택`} onClick={()=>onGold(c.cardId)}><Atlas panel="GOLD"/><strong>{c.value}<small> GOLD</small></strong></button>)}</div></>:<p>{name(g.activePlayerId)}님이 금 카드를 선택하고 있습니다.</p>)}
 {g.phase==='ROUND_RESULT'&&<><p>확인 {g.confirmedPlayerIds.length} / {g.playerStates.length} · 모두 확인하면 다음 라운드를 시작합니다.</p><button className="sab-primary" disabled={!enabled||g.confirmedPlayerIds.includes(g.privateState.playerId)} onClick={onConfirm}>{g.confirmedPlayerIds.includes(g.privateState.playerId)?'다른 참가자 확인 대기':'확인 · 다음 라운드'}</button></>}
 {g.phase==='FINISHED'&&<>{!cancelled&&<div className="sab-final-scores">{[...g.result.scores].sort((a,b)=>b.gold-a.gold).map(p=><div key={p.playerId}><span>{name(p.playerId)}</span><b>{p.gold}<small> 금</small></b></div>)}</div>}{isHost?<button className="sab-primary" disabled={!enabled} onClick={onRematch}>같은 방에서 다시 하기</button>:<p>방장이 다음 게임을 선택할 수 있습니다.</p>}</>}
 </section>;
}
