import { CityCardinalBuild } from './CityCardinalBuild.js';
import { CityAbbotIncome, CityAbbotTribute } from './CityAbbotAbility.js';
import { useCitySound } from "./city-role-sound.js";
import { useEffect, useId, useState } from 'react';
import { CITY_ALL_ROLE_IDS, CITY_EXPANDED_ROLES, CITY_SPECIAL_BUILDINGS, type CityExpansionAction, type CityExpansionClientCommand, type CityRolePlayingPlatformSnapshotV2, type CityRoleFinishedPlatformSnapshotV2, type CityRoleId, type CityPublicBuilding } from '@hangul-rummikub/shared';
import { createRequestId } from '../../lib/request-id.js';
import { CityBuildingFace } from './CityBuildingFace.js';
import { CityExpandedTurnHud } from './CityExpandedTurnHud.js';
import { CitySecretDraft } from './CitySecretDraft.js';
import { CityResourceTokens, CityRoleTrack } from './CityTabletop.js';
import { CityIcon, CityRoleEmblem } from './CityVisuals.js';
import { CityRoleTargets } from './CityRoleTargets.js';
import { CityWizardTargets, CityWizardChoices } from './CityWizardAbility.js';
import { CityWarlordTargets } from './CityWarlordTargets.js';
import { cityBuildPreview } from './city-build-preview.js';
import { CityTurnSteps } from './CityTurnSteps.js';
import { CityConstructionProgress } from './CityConstructionProgress.js';
import { CityExpandedResults } from './CityExpandedResults.js';
import { CityExpandedReference } from './CityExpandedReference.js';
import type { CityActionIntent } from './city-role-actions.js';
import { CITY_CATEGORY_LABELS } from './city-role-ui.js';

type Snapshot = CityRolePlayingPlatformSnapshotV2 | CityRoleFinishedPlatformSnapshotV2;
export function CityExpandedScreen({ snapshot: s, connected, pending, errorMessage, onCommand, onAction, onLeave }: { snapshot: Snapshot; connected: boolean; pending: boolean; errorMessage: string | null; onCommand(command: CityExpansionClientCommand): Promise<void>; onAction(intent: CityActionIntent): void; onLeave(): void }) {
  const handId = useId();
  const sound = useCitySound(s, null, !connected, true);
  const game = s.game, e = game.expansion!, me = game.playerStates.find(p => p.playerId === s.self.playerId)!;
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [selected, setSelected] = useState<string[]>([]);
  const [roles, setRoles] = useState<CityRoleId[]>([]), [target, setTarget] = useState(''), [targetCard, setTargetCard] = useState(''), [own, setOwn] = useState(''), [buildCard, setBuildCard] = useState('');
  const [category, setCategory] = useState<CityPublicBuilding['category']>('TRADE');
  const [displayTime, setDisplayTime] = useState(s.serverTime as number);
  useEffect(() => { const started = Date.now(); setDisplayTime(s.serverTime); const timer = setInterval(() => setDisplayTime(s.serverTime + Date.now() - started), 500); return () => clearInterval(timer); }, [s.serverTime]);
  const token = game.phase === 'FINISHED' ? 'finished' : game.window.actionId;
  useEffect(() => { setSelected([]); setRoles([]); setTargetCard(''); setOwn(''); setError(''); }, [token]);
  const active = game.phase !== 'FINISHED' && game.window.activePlayerId === s.self.playerId;
  const remainingSeconds = game.phase === 'FINISHED' ? 0 : Math.max(0, Math.ceil((game.window.deadlineAt - displayTime) / 1000));
  const disabled = !connected || !active || busy || pending || remainingSeconds === 0;
  const budget = game.phase === 'ROLE_ACTION' ? game.privateState.action : undefined;
  const ready = !disabled && budget?.acquisition === 'COMPLETE' && e.pending === null;
  const role = game.phase === 'ROLE_ACTION' ? CITY_EXPANDED_ROLES.find(r => r.id === e.settings.roles[Number(game.window.activeRoleId.slice(-2)) - 1]) : undefined;
  const mustUseAbility = role?.id === 'WITCH' || role?.id === 'EMPEROR' && game.playerStates.some(p => !p.forfeited && p.playerId !== me.playerId && p.playerId !== game.leaderPlayerId);
  const canEnd = ready && (!mustUseAbility || Boolean(budget?.abilityUsed));
  const previewBuild = (card: CityPublicBuilding) => cityBuildPreview(card, { buildings: me.builtBuildings, gold: me.gold, job: active ? role?.id : undefined, buildingsBuilt: budget?.buildingsBuilt ?? 0, taxCollector: active && e.settings.roles.includes('TAX_COLLECTOR') });
  const activeSpecials = CITY_SPECIAL_BUILDINGS.filter(b => role?.id !== 'WITCH' && ['LABORATORY','SMITHY','MUSEUM','ARMORY'].includes(b.effect) && me.builtBuildings.some(card => card.templateId === b.templateId));
  const roleTargeting = role && ['ASSASSIN','THIEF','WITCH','MAGISTRATE','BLACKMAILER'].includes(role.id);
  const targetCount = role?.id === 'MAGISTRATE' ? 3 : role?.id === 'BLACKMAILER' ? 2 : 1;
  const targetVerb = role?.id === 'ASSASSIN' ? '암살' : role?.id === 'THIEF' ? '도둑질' : role?.id === 'WITCH' ? '홀림' : role?.id === 'MAGISTRATE' ? '영장' : '협박';
  const frameworks = me.builtBuildings.filter(b => b.templateId === 'CB-SP-06');
  const alternativeCards = game.privateState.hand.filter(b => role?.id !== 'WITCH' && role?.id !== 'NAVIGATOR' && b.cost > 0 && (frameworks.length > 0 || b.templateId === 'CB-SP-29' || b.templateId === 'CB-SP-18' && me.builtBuildings.length > 0));
  const alternativeCard = alternativeCards.find(b => b.cardId === buildCard);
  const sacrificeCards = alternativeCard?.templateId === 'CB-SP-18' ? me.builtBuildings : frameworks;
  const sacrifice = sacrificeCards.find(b => b.cardId === own);
  const nickname = (id: string) => s.room.players.find(p => p.playerId === id)?.nickname ?? '참가자';
  const roleName = (id: CityRoleId) => CITY_EXPANDED_ROLES.find(r => r.id === e.settings.roles[Number(id.slice(-2)) - 1])?.name ?? id;
  const describeRole = (id: CityRoleId) => ({ name: roleName(id), summary: CITY_EXPANDED_ROLES.find(r => r.id === e.settings.roles[Number(id.slice(-2)) - 1])?.text ?? '' });
  const roleFace = (id: CityRoleId) => <><CityRoleEmblem roleId={id} /><span className="city-role-order">등장 순서 {Number(id.slice(-2))}</span><strong>{roleName(id)}</strong><p>{describeRole(id).summary}</p></>;
  const toggle = (id: string) => setSelected(xs => xs.includes(id) ? xs.filter(x => x !== id) : [...xs, id]);
  async function send(action: CityExpansionAction) {
    if (game.phase === 'FINISHED' || disabled) return;
    setBusy(true); setError('');
    try { await onCommand({ kind: 'city:expansionAction', protocolVersion: 1, requestId: createRequestId(), gameId: game.gameId, actionId: game.window.actionId, expectedGameRevision: game.gameRevision, payload: action }); setSelected([]); }
    catch (e) { setError(e instanceof Error ? e.message : '행동을 처리하지 못했습니다.'); } finally { setBusy(false); }
  }
  const rolePayload = (): CityExpansionAction => ({ command: 'ROLE', ...(target ? { targetPlayerId: target } : {}), ...(targetCard ? { cardId: targetCard } : {}), ...(own ? { ownCardId: own } : {}), cardIds: selected, roleIds: roles, category });
  function cardsView(cards: readonly CityPublicBuilding[], mode: 'hand' | 'city' | 'choice', owner?: string) {
    return <div className={`city-expanded-cards city-expanded-cards-${mode}`}>{cards.map(card => { const build = previewBuild(card); return <div key={card.cardId} className={`city-expanded-card${mode === 'hand' && ready && !build.reason ? ' is-buildable' : ''} ${selected.includes(card.cardId) || targetCard === card.cardId ? 'is-selected' : ''}`}>
      <button className="city-card-select" aria-label={`${card.name} 선택`} aria-pressed={selected.includes(card.cardId) || targetCard === card.cardId} onClick={() => { if (mode === 'city') { setTarget(owner ?? ''); setTargetCard(card.cardId); if (owner === s.self.playerId) toggle(card.cardId); } else toggle(card.cardId); }}><CityBuildingFace card={card} rulesVersion="city-rules-v3" /></button>
      {mode === 'hand' && <div className="city-build-offer">
        {card.templateId !== 'CB-SP-24' && <div className="city-build-price"><span><CityIcon name="coin" />건설 <b>{build.cost}</b> 금화</span>{build.discount > 0 && <small>공장 −{build.discount}</small>}{build.tax > 0 && <small>건설 후 세금 +{build.tax}</small>}</div>}
        <p className={ready && !build.reason ? 'city-build-ready' : ''}>{build.reason ?? (game.phase === 'FINISHED' ? '게임 종료' : !active || game.phase === 'ROLE_SELECTION' ? '내 행동 차례에 건설' : e.pending ? '진행 중인 선택을 마치세요' : budget?.acquisition !== 'COMPLETE' ? '자원을 받은 뒤 건설' : !connected ? '연결 복구 중' : remainingSeconds === 0 ? '행동 시간 종료' : busy || pending ? '처리 중' : '건설 가능')}{build.freeBuild && !build.restriction && <span> · 건설 횟수 제외</span>}</p>
        {build.alternative && <p className="city-build-alternative">{build.alternative}</p>}
        <button className="city-inline-build" aria-label={`${card.name} · ${build.cost}금화로 건설`} disabled={!ready || Boolean(build.reason)} onClick={() => void send({ command: 'BUILD', cardId: card.cardId })}>건설</button>
      </div>}
      {e.decorated.includes(card.cardId) && <span className="city-card-ribbon">장식 +1</span>}
      {e.museum.some(row => row.buildingId === card.cardId) && <small>보관 {e.museum.find(row => row.buildingId === card.cardId)?.count}장</small>}
    </div>; })}</div>;
  }
  return <main className="city-shell city-expanded-page">
    <header className="city-expanded-hero"><div><span className="city-eyebrow">CITY · {e.settings.enabled ? 'EXPANDED' : 'CLASSIC'}</span><h1>도시의 다음 장</h1><p>{game.roundNumber}라운드 · 왕관 {nickname(game.leaderPlayerId)} · {game.phase === 'FINISHED' ? '게임 종료' : `${nickname(game.window.activePlayerId)}님의 ${game.phase === 'ROLE_SELECTION' ? '직업 선택' : role?.name ?? '차례'}`}</p></div><div className="city-wallet"><b>{me.gold}</b> 금화<span>{me.handCount}장 보유 · {me.builtBuildings.length}채 건설</span></div><div className="city-expanded-sound"><CityExpandedReference snapshot={s} /><button aria-pressed={sound.enabled} onClick={sound.toggle}>사운드 {sound.enabled ? "켜짐" : "꺼짐"}</button><label>효과음 볼륨<input aria-label="효과음 볼륨" type="range" min="0" max="100" value={sound.volume} onChange={event => sound.changeVolume(Number(event.target.value))}/></label><button onClick={onLeave}>나가기</button></div></header>
    {game.phase !== 'FINISHED' && <div className="city-mobile-status"><CityExpandedTurnHud game={game} viewerId={s.self.playerId} actor={nickname(game.window.activePlayerId)} remainingSeconds={remainingSeconds} roleName={role?.name ?? ''} /><div className="city-mobile-resources" aria-label="내 자원 현황"><CityResourceTokens gold={me.gold} handCount={me.handCount} score={me.scorePreview} /></div></div>}
    {game.phase !== 'FINISHED' && <CityRoleTrack game={game} players={s.room.players} />}
    <section className={`city-private-summary${game.phase !== 'FINISHED' ? ' has-mobile-resources' : ''}`} aria-label="내 비공개 역할과 금화"><div><p className="city-eyebrow">나에게만 보임</p><h2>이번 라운드의 내 직업</h2><div className="city-expanded-own-roles">{game.privateState.selectedRoleIds.map(id => <span className="city-expanded-own-role" key={id}><CityRoleEmblem roleId={id}/><strong>{roleName(id)}</strong></span>)}{game.privateState.selectedRoleIds.length === 0 && <p>아직 선택하지 않음</p>}</div></div><CityResourceTokens gold={me.gold} handCount={me.handCount} score={me.scorePreview} /></section>
    {!connected && <p role="status">연결을 복구하고 있습니다. 행동은 연결 후 가능합니다.</p>}
    {(error || errorMessage) && <p className="city-expanded-error" role="alert">{error || errorMessage}</p>}
    <div className="city-action-row" aria-label="공개된 지목">{e.disabledRole && <span>암살 대상 · {roleName(e.disabledRole)}</span>}{e.robbedRole && <span>도둑 대상 · {roleName(e.robbedRole)}</span>}{e.witchTarget && <span>홀린 직업 · {roleName(e.witchTarget)}</span>}{e.warrants.length > 0 && <span>영장 · {e.warrants.map(roleName).join(", ")}</span>}{e.threats.length > 0 && <span>협박 · {e.threats.map(roleName).join(", ")}</span>}{game.privateState.expansion?.realWarrant && <span>나의 진짜 영장 · {roleName(game.privateState.expansion.realWarrant)}</span>}{game.privateState.expansion?.realThreat && <span>나의 진짜 협박 · {roleName(game.privateState.expansion.realThreat)}</span>}{e.settings.roles.includes("TAX_COLLECTOR") && <span>세금 보관 · {e.tax} 금화</span>}</div>
    {game.phase === 'FINISHED' ? <CityExpandedResults game={game} players={s.room.players}/> : (game.phase === 'ROLE_SELECTION' || active || e.pending !== null) && <section aria-label={game.phase === 'ROLE_SELECTION' ? '직업 선택' : '직업 행동'} className={`city-expansion-panel${game.phase === 'ROLE_SELECTION' ? ' city-selection' : ''}`}>
      {game.phase === 'ROLE_SELECTION' ? <><h2>{active ? '이번 라운드의 직업을 고르세요' : '비밀리에 직업을 선택하고 있습니다'}</h2><p>내 직업: {game.privateState.selectedRoleIds.map(roleName).join(', ') || '아직 선택하지 않음'}</p>{game.secretPairDraft && active ? <CitySecretDraft discardRequired={game.draftDiscardRequired ?? true} automaticLast={game.roleDraftVersion !== "city-draft-v3"} selectionSeconds={(game.window.deadlineAt - game.window.startedAt) / 1000} key={token} roles={game.privateState.availableRoleIds ?? []} locked={disabled} describeRole={describeRole} onAction={onAction} /> : <><div className="city-role-grid">{(game.privateState.availableRoleIds ?? []).map(id => <button key={id} className={`city-role-card${roles.includes(id) ? ' is-kept' : ''}`} data-role={id} disabled={disabled} aria-label={`${roleName(id)} 선택`} aria-pressed={roles.includes(id)} onClick={() => setRoles(xs => xs.includes(id) ? [] : [id])}>{roleFace(id)}<span className="city-role-pick">{roles.includes(id) ? '✓ 선택됨' : '이 직업 선택'}</span></button>)}</div>{active && <button className="city-primary" disabled={disabled || roles.length !== 1} onClick={() => { if (roles[0]) onAction({ kind: 'city:selectRole', payload: { roleId: roles[0] } }); }}>직업 확정</button>}</>}</> : <>
        {e.pending === 'WIZARD' ? <div className="city-choice-panel city-wizard-panel"><h3>{active ? '상대 손패에서 카드를 선택하세요' : '마법사가 카드를 선택하고 있습니다'}</h3>{active && <CityWizardChoices cards={game.privateState.expansion?.choiceCards ?? []} buildings={me.builtBuildings} gold={me.gold} taxCollector={e.settings.roles.includes('TAX_COLLECTOR')} disabled={disabled} onDecide={(cardId, choice) => void send({ command: 'DECIDE', cardId, choice })}/>}</div> : e.pending && <div className="city-choice-panel"><h3>{{ WIZARD: '가져올 카드를 선택하세요', SEER: '받았던 상대들에게 돌려줄 카드를 순서대로 선택하세요', SCHOLAR: '남길 카드 1장을 선택하세요', THEATER: '역할을 교환하시겠어요?', BRIBE: '금화 절반을 내고 협박을 피하시겠어요?', BLACKMAIL: '협박을 공개하시겠어요?', CONFISCATE: '이 건물을 몰수하시겠어요?', EMPEROR: '왕관을 받을 사람을 정하세요' }[e.pending]}</h3>
          {active && <>{cardsView(game.privateState.expansion?.choiceCards ?? [], 'choice')}{e.pending === 'SEER' && <p>돌려줄 순서: {game.privateState.expansion?.recipients.map(nickname).join(' → ')}. 아래 손패에서 순서대로 선택하세요.</p>}
            {(e.pending === 'THEATER' || e.pending === 'EMPEROR') && <><select aria-label="교환할 상대" value={target} onChange={ev => setTarget(ev.target.value)}><option value="">상대 선택</option>{game.playerStates.filter(p => !p.forfeited && p.playerId !== me.playerId).map(p => <option key={p.playerId} value={p.playerId}>{nickname(p.playerId)}</option>)}</select>{e.pending === 'THEATER' && <select aria-label="내 역할" value={roles[0] ?? ''} onChange={ev => { const id = CITY_ALL_ROLE_IDS.find(id => id === ev.target.value); setRoles(id ? [id] : []); }}><option value="">교환할 내 역할</option>{game.privateState.selectedRoleIds.map(id => <option key={id} value={id}>{roleName(id)}</option>)}</select>}</>}
            <div className="city-action-row">{e.pending === 'SCHOLAR' || e.pending === 'SEER' ? <button disabled={disabled || (e.pending === 'SCHOLAR' ? selected.length !== 1 : selected.length !== game.privateState.expansion?.recipients.length)} onClick={() => void send({ command: 'DECIDE', ...(e.pending === 'SCHOLAR' ? { cardId: selected[0]! } : { cardIds: selected }) })}>카드 선택 확정</button> : <><button disabled={disabled || (e.pending === 'THEATER' && (!target || roles.length !== 1)) || (e.pending === 'EMPEROR' && !target)} onClick={() => void send({ command: 'DECIDE', choice: 'YES', ...(target ? { targetPlayerId: target } : {}), roleIds: roles })}>{e.pending === 'EMPEROR' ? '왕관 전달' : '예'}</button>{e.pending !== 'EMPEROR' && <button disabled={disabled} onClick={() => void send({ command: 'DECIDE', choice: 'NO' })}>아니요</button>}</>}</div></>}
        </div>}
        {active && <>{budget && !e.pending && <CityTurnSteps acquisition={budget.acquisition} handId={handId} />}{budget?.acquisition === 'NOT_TAKEN' && !e.pending && <div className="city-acquire-options"><button disabled={disabled} onClick={() => onAction({ kind: 'city:takeIncome', payload: {} })}><CityIcon name="coin" /><span>금화 {me.builtBuildings.some(b => b.templateId === 'CB-SP-07') ? 3 : 2}개 받기<small>건설에 쓸 금화를 확보합니다</small></span></button><button disabled={disabled} onClick={() => onAction({ kind: 'city:drawBuildingCards', payload: {} })}><CityIcon name="cards" /><span>건물 카드 뽑기<small>새로운 건물을 손패에 추가합니다</small></span></button></div>}
        {game.privateState.pendingCards && <div className="city-expanded-cards">{game.privateState.pendingCards.map(card => <div className="city-expanded-card" key={card.cardId}><button className="city-card-select" disabled={disabled} onClick={() => onAction({ kind: 'city:chooseBuildingCard', payload: { cardId: card.cardId } })}><CityBuildingFace card={card} rulesVersion="city-rules-v3"/><b>이 카드 받기</b></button></div>)}</div>}
        {budget?.acquisition === 'COMPLETE' && !e.pending && <div className="city-ability-controls">{role?.id === 'ABBOT' && <CityAbbotIncome key={token} buildings={me.builtBuildings} ready={ready} used={Boolean(game.privateState.expansion?.incomeUsed)} onCollect={goldCount => void send({ command: 'INCOME', goldCount })}/>}<div className="city-action-row">{role && ['KING','EMPEROR','PATRICIAN','BISHOP','CARDINAL','MERCHANT','TRADER','WARLORD','DIPLOMAT','MARSHAL'].includes(role.id) && <button disabled={!ready || game.privateState.expansion?.incomeUsed} onClick={() => void send({ command: 'INCOME' })}>건물 종류별 수입 받기</button>}</div>
          {role?.id === 'CARDINAL' && <CityCardinalBuild key={token} hand={game.privateState.hand} buildings={me.builtBuildings} gold={me.gold} buildingsBuilt={budget.buildingsBuilt} taxCollector={e.settings.roles.includes('TAX_COLLECTOR')} players={game.playerStates} viewerId={me.playerId} nickname={nickname} ready={ready} onBuild={(cardId, cardIds, targetPlayerId) => void send({ command: 'BUILD', cardId, cardIds, targetPlayerId })}/>}
          {role?.id !== 'CARDINAL' && (role && !['KING','PATRICIAN','BISHOP','MERCHANT','ALCHEMIST','TRADER','ARCHITECT','QUEEN','TAX_COLLECTOR'].includes(role.id) || me.builtBuildings.some(b => b.templateId === 'CB-SP-01')) && <details open><summary>직업 능력 사용</summary>{role?.id === 'ABBOT' ? <CityAbbotTribute key={token} players={game.playerStates} viewerId={me.playerId} nickname={nickname} ready={ready} used={budget.abilityUsed} onCollect={targetPlayerId => void send({ command: 'ROLE', targetPlayerId })}/> : role?.id === 'WIZARD' ? <CityWizardTargets key={token} players={game.playerStates} viewerId={me.playerId} nickname={nickname} ready={ready} used={budget.abilityUsed} onInspect={targetPlayerId => void send({ command: 'ROLE', targetPlayerId })}/> : role?.id === 'WARLORD' ? <CityWarlordTargets game={game} viewerId={me.playerId} gold={me.gold} ready={ready} used={budget.abilityUsed} targetPlayerId={target} targetCardId={targetCard} nickname={nickname} onSelect={(playerId, cardId) => { setTarget(playerId); setTargetCard(cardId); }} onDestroy={(playerId, cardId) => void send({ command: 'ROLE', targetPlayerId: playerId, cardId })}/> : <><div className="city-ability-inputs">
          {roleTargeting && <CityRoleTargets targets={CITY_ALL_ROLE_IDS.slice(role.rank, e.settings.roles.length).map(id => ({ id, name: roleName(id), reason: ['THIEF','BLACKMAILER'].includes(role.id) && id === e.disabledRole ? '암살된 직업' : ['THIEF','BLACKMAILER'].includes(role.id) && id === e.witchTarget ? '홀린 직업' : null }))} selected={roles} count={targetCount} verb={targetVerb} disabled={!ready} used={budget.abilityUsed} onChange={setRoles} onConfirm={() => { if (role.id === 'ASSASSIN' || role.id === 'THIEF') { if (roles[0]) onAction({ kind: 'city:useRoleAbility', payload: { ability: role.id === 'ASSASSIN' ? 'MARK_ROLE_DISABLED' : 'MARK_ROLE_GOLD_TRANSFER', targetRoleId: roles[0] } }); } else void send({ command: 'ROLE', roleIds: roles }); }}/>}
          {(role && ['MAGICIAN','SPY','WIZARD','EMPEROR','CARDINAL','WARLORD','DIPLOMAT','MARSHAL'].includes(role.id) || me.builtBuildings.some(b => b.templateId === 'CB-SP-01')) && <label>상대<select value={target} onChange={ev => { setTarget(ev.target.value); setTargetCard(''); }}><option value="">플레이어 선택</option>{game.playerStates.filter(p => !p.forfeited).map(p => <option key={p.playerId} value={p.playerId}>{nickname(p.playerId)}</option>)}</select></label>}
          {(role && ['WARLORD','DIPLOMAT','MARSHAL'].includes(role.id) || me.builtBuildings.some(b => b.templateId === 'CB-SP-01')) && <label>상대 건물<select value={targetCard} onChange={ev => setTargetCard(ev.target.value)}><option value="">건물 선택</option>{game.playerStates.find(p => p.playerId === target)?.builtBuildings.map(b => <option key={b.cardId} value={b.cardId}>{b.name} · {b.cost}</option>)}</select></label>}
          {role?.id === 'DIPLOMAT' && <label>내 건물<select value={own} onChange={ev => setOwn(ev.target.value)}><option value="">건물 선택</option>{me.builtBuildings.map(b => <option key={b.cardId} value={b.cardId}>{b.name}</option>)}</select></label>}
          {role?.id === 'SPY' && <label>지목할 종류<select value={category} onChange={ev => { const c = Object.keys(CITY_CATEGORY_LABELS).find(c => c === ev.target.value); if (c) setCategory(c as CityPublicBuilding['category']); }}>{Object.entries(CITY_CATEGORY_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>}
          </div>{!roleTargeting && <p className="city-muted">카드를 사용하는 능력은 아래 손패나 내 도시에서 카드를 선택하세요. 선택 {selected.length}장</p>}
          <div className="city-action-row">{role?.id === 'MAGICIAN' ? <><button disabled={!ready || budget.abilityUsed || !target} onClick={() => { const p = game.playerStates.find(p => p.playerId === target); if (p) onAction({ kind: 'city:useRoleAbility', payload: { ability: 'EXCHANGE_HANDS', targetPlayerId: p.playerId } }); }}>손패 전체 교환</button><button disabled={!ready || budget.abilityUsed || !selected.length} onClick={() => onAction({ kind: 'city:useRoleAbility', payload: { ability: 'REPLACE_OWN_CARDS', cardIds: game.privateState.hand.filter(c => selected.includes(c.cardId)).map(c => c.cardId) } })}>선택한 손패 교체</button></> : role && ['EMPEROR','NAVIGATOR'].includes(role.id) ? <><button disabled={!ready || budget.abilityUsed} onClick={() => void send({ ...rolePayload(), choice: 'GOLD' })}>금화로 받기</button><button disabled={!ready || budget.abilityUsed} onClick={() => void send({ ...rolePayload(), choice: 'CARDS' })}>카드로 받기</button></> : role && !roleTargeting && !['KING','PATRICIAN','BISHOP','CARDINAL','MERCHANT','ALCHEMIST','TRADER','ARCHITECT','QUEEN','TAX_COLLECTOR'].includes(role.id) && <button disabled={!ready || budget.abilityUsed} onClick={() => void send(rolePayload())}>{role.name} 능력 사용</button>}</div></>}</details>}
          {activeSpecials.length > 0 && <details><summary>특수 건물 사용 · {activeSpecials.map(b => b.name).join(' · ')}</summary>
            {(role?.id === 'WIZARD' || role?.id === 'ABBOT' || role?.id === 'CARDINAL') && activeSpecials.some(b => b.effect === 'ARMORY') && <div className="city-ability-inputs"><label>병기고 대상 도시<select value={target} onChange={ev => { setTarget(ev.target.value); setTargetCard(''); }}><option value="">도시 선택</option>{game.playerStates.filter(p => !p.forfeited).map(p => <option key={p.playerId} value={p.playerId}>{nickname(p.playerId)}</option>)}</select></label><label>병기고 대상 건물<select value={targetCard} onChange={ev => setTargetCard(ev.target.value)}><option value="">건물 선택</option>{game.playerStates.find(p => p.playerId === target)?.builtBuildings.map(b => <option key={b.cardId} value={b.cardId}>{b.name}</option>)}</select></label></div>}{activeSpecials.length > 0 && <><p>내 도시에 지은 특수 건물의 능력입니다. 직업 능력과 별도로 사용합니다.</p><div className="city-action-row">{activeSpecials.map(b => <button key={b.effect} disabled={!ready || game.privateState.expansion?.usedSpecials.includes(b.effect)} onClick={() => void send({ command: 'SPECIAL', effect: b.effect, ...(b.effect === 'ARMORY' ? { targetPlayerId: target, cardId: targetCard } : selected[0] ? { cardId: selected[0] } : {}) })}>{b.name} 사용</button>)}</div></>}
          </details>}
          {alternativeCards.length > 0 && <details><summary>대체 건설 · {frameworks.length > 0 ? '골조' : [...new Set(alternativeCards.map(b => b.name))].join(' · ')}</summary><p>도둑 소굴·묘지·골조의 능력으로 건설합니다. 손패로 지불할 카드는 아래에서 선택하고, 건설할 카드 자체는 포함하지 마세요.</p><div className="city-ability-inputs">
              <label>건설할 카드<select value={alternativeCard?.cardId ?? ''} onChange={ev => { setBuildCard(ev.target.value); setOwn(''); }}><option value="">선택하세요</option>{alternativeCards.map(b => <option key={b.cardId} value={b.cardId}>{b.name}</option>)}</select></label>
              {sacrificeCards.length > 0 && <label>희생할 내 건물<select value={sacrifice?.cardId ?? ''} onChange={ev => setOwn(ev.target.value)}><option value="">희생하지 않음</option>{sacrificeCards.map(b => <option key={b.cardId} value={b.cardId}>{b.name}</option>)}</select></label>}
            </div><button disabled={!ready || !alternativeCard} onClick={() => { if (alternativeCard) void send({ command: 'BUILD', cardId: alternativeCard.cardId, cardIds: selected, ...(sacrifice ? { ownCardId: sacrifice.cardId } : {}) }); }}>선택한 방식으로 건설</button>
          </details>}
        </div>}</>}
      </>}
    </section>}
    {(game.privateState.expansion?.inspectedCards.length ?? 0) > 0 && <section className="city-expansion-panel"><h2>확인한 상대 손패</h2>{cardsView(game.privateState.expansion!.inspectedCards, 'choice')}</section>}
    <section id={handId} className="city-expansion-panel city-hand"><CityConstructionProgress buildings={me.builtBuildings} ending={game.firstCompletion !== null} finished={game.phase === 'FINISHED'} /><h2>나의 손패 <span>{me.handCount}</span></h2><p className="city-muted">카드를 누르면 능력에 사용할 카드로 선택됩니다.</p>{cardsView(game.privateState.hand, 'hand')}{active && game.phase === 'ROLE_ACTION' && <footer className="city-turn-finish"><div><strong>3 · 차례 마치기</strong><p>{e.pending ? '진행 중인 선택을 먼저 마치세요.' : budget?.acquisition !== 'COMPLETE' ? '자원을 먼저 받으세요.' : mustUseAbility && !budget.abilityUsed ? '직업의 필수 능력을 먼저 사용하세요.' : '능력과 건설을 마쳤다면 다음 차례로 넘어가세요.'}</p></div><button disabled={!canEnd} onClick={() => onAction({ kind: 'city:endTurn', payload: {} })}>차례 마치기 →</button></footer>}</section>
    <section className="city-cities">{game.playerStates.map(p => <article className={`city-expansion-panel city-public-city${p.playerId === me.playerId ? ' is-mine' : ''}${game.phase !== 'FINISHED' && p.playerId === game.window.activePlayerId ? ' is-active' : ''}`} key={p.playerId}><h2>{nickname(p.playerId)}의 도시 {p.playerId === game.leaderPlayerId ? '♛' : ''}</h2>{p.forfeited && <p className="city-muted">기권</p>}<CityConstructionProgress variant="public" cityName={`${nickname(p.playerId)}의 도시`} buildings={p.builtBuildings} ending={game.firstCompletion !== null} finished={game.phase === 'FINISHED'} /><CityResourceTokens gold={p.gold} handCount={p.handCount} score={p.scorePreview} />{cardsView(p.builtBuildings, 'city', p.playerId)}</article>)}</section>
  </main>;
}
