import { useEffect, useRef, useState } from 'react';
import { CENTURY_COLORS, PROTOCOL_VERSION, centurySum, type CenturyAction, type CenturyClientCommand, type CenturyMerchant, type CenturyPoint, type CenturySpices } from '@hangul-rummikub/shared';
import type { CenturyWebSnapshot } from '../../lib/snapshot-wire-decoder.js';
import { getGameStartControl } from '../../lib/game-start.js';
import { createRequestId } from '../../lib/request-id.js';
import { CenturyCommandRejected } from '../../lib/century-command-error.js';
import { CENTURY_LABELS, CENTURY_SPICE_NAMES, CENTURY_ACTION_LABELS, centuryCardText, emptyCenturyDraft, previewCentury, type CenturyDraft } from './ui.js';
import { useCenturySound } from './sound.js';
type Props=Readonly<{snapshot:CenturyWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(command:CenturyClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void}>;
type Game=NonNullable<CenturyWebSnapshot['game']>;
function Spices({values,all=false}:{values:CenturySpices;all?:boolean}){return <span className="ct-spices">{CENTURY_COLORS.filter(i=>all||values[i]>0).map(i=><span className={`ct-spice ct-spice-${i}`} key={i} aria-label={`${CENTURY_LABELS[i]} ${CENTURY_SPICE_NAMES[i]} ${values[i]}개`}><i aria-hidden="true">{['●','◆','▲','■'][i]}</i><span>{CENTURY_LABELS[i]}</span><b>{values[i]}</b></span>)}{!all&&centurySum(values)===0?<span className="ct-muted">없음</span>:null}</span>;}
function Merchant({card,selected=false,disabled=false,onClick}:{card:CenturyMerchant;selected?:boolean;disabled?:boolean;onClick?:()=>void}){return <button type="button" className={`ct-card ct-merchant ct-${card.kind.toLowerCase()}`} aria-label={centuryCardText(card)} aria-pressed={selected} disabled={disabled} onClick={onClick}>
 <span className="ct-card-label">{CENTURY_ACTION_LABELS[card.kind]}</span><span className="ct-portrait" aria-hidden="true"/>
 <span className="ct-effect">{card.kind==='UPGRADE'?<><b className="ct-upgrade-symbol">↑ {card.steps}</b><small>최대 {card.steps}단계</small><span>노랑 → 빨강 → 초록 → 갈색</span></>:<>{card.kind==='TRADE'?<><Spices values={card.cost}/><span className="ct-arrow">↓</span></>:<small>향신료 획득</small>}<Spices values={card.gain}/></>}</span>
 </button>;}
function PointCard({card,bonus,disabled,onClick,selected=false}:{card:CenturyPoint;bonus:string;disabled:boolean;onClick():void;selected?:boolean}){return <button type="button" className="ct-card ct-point" aria-label={`${card.points}점 · ${CENTURY_COLORS.filter(i=>card.cost[i]).map(i=>`${CENTURY_LABELS[i]} ${card.cost[i]}`).join(' ')}${bonus?' · '+bonus:''}`} aria-pressed={selected} disabled={disabled} onClick={onClick}><span className="ct-point-art" aria-hidden="true"/><span className="ct-point-value">{card.points}<small>점</small></span><span className="ct-point-cost"><Spices values={card.cost}/></span><span className={bonus?'ct-bonus':'ct-bonus ct-no-bonus'}>{bonus||'향신료 납품'}</span></button>;}
export function CenturyScreen(props:Props){
 const s=props.snapshot,start=getGameStartControl(s,props.pending||!props.connected),sound=useCenturySound(s.game,s.self.playerId,props.connected);
 return <section className="century-screen" aria-label="센추리 향신료의 길" onPointerDown={()=>sound.unlock()} onKeyDown={()=>sound.unlock()}>
  <header className="ct-header"><div><span className="ct-eyebrow">CENTURY · SPICE ROAD</span><h1>센추리 <span>향신료의 길</span></h1></div><div className="ct-room"><span>방 {s.room.roomCode}</span><span role="status">{props.connectionLabel}</span><button onClick={props.onCopy} disabled={props.pending}>초대 링크</button><button onClick={props.onLeave} disabled={props.pending}>나가기</button></div></header>
  <div className="ct-tools"><details><summary>게임 방법</summary><div className="ct-help"><p>차례마다 카드 사용, 상인 획득, 휴식, 점수 획득 중 하나를 합니다. 교환은 반복할 수 있고 업그레이드는 같은 향신료를 연속으로 올릴 수 있습니다.</p><p>상인 카드 왼쪽마다 향신료 1개를 먼저 놓고, 가져온 카드 위 향신료를 받습니다. 휴식하면 사용한 카드 전부가 손패로 돌아옵니다.</p><p>턴 종료 시 향신료는 10개까지입니다. 넘는 만큼 직접 골라 반환합니다. 2–3인은 목표 6장, 4–5인은 5장을 모으면 마지막 라운드입니다.</p><p>선공 직전 자리까지 진행한 뒤 점수 카드 + 금화 3점 + 은화 1점 + 노랑 외 향신료 각 1점으로 정산합니다. 동점은 선공 기준 뒤쪽 차례가 승리합니다.</p><p>상대 손패와 획득 점수 카드 내용은 비공개입니다. 시간 제한은 없고 새로고침해도 같은 자리로 돌아옵니다. 나가기는 게임을 취소합니다.</p></div></details><div className="ct-audio"><button type="button" aria-pressed={sound.volume===0} onClick={()=>sound.changeVolume(sound.volume===0?55:0)}>{sound.volume===0?'소리 켜기':'음소거'}</button><label>효과음 음량 <input aria-label="효과음 음량" type="range" min="0" max="100" value={sound.volume} onChange={e=>sound.changeVolume(Number(e.target.value))}/></label><button type="button" onClick={()=>sound.play('CLAIM')}>소리 듣기</button></div></div>
  {props.error&&<p role="alert" className="ct-error">{props.error}</p>}
  {s.game===null?<div className="ct-lobby"><div className="ct-lobby-copy"><span className="ct-eyebrow">YOUR CARAVAN AWAITS</span><h2>향신료에서 시작되는<br/>나만의 교역 이야기</h2><p>상인을 만나고, 향신료를 바꾸고,<br/>가장 값진 교역로를 완성하세요.</p><div className="ct-seats">{s.room.players.map(p=><span key={p.playerId}><b>{p.nickname}</b> {p.isHost?'♛ ':''}{p.connectionStatus==='CONNECTED'?'접속 중':'재접속 대기'}</span>)}</div><p>{start.guidance}</p><button className="ct-primary" disabled={!start.canStart} onClick={props.onStart}>교역 시작</button><p className="ct-muted">2–5인 · 기본판 · 시간 제한 없음</p></div></div>:<CenturyTable key={s.game.gameId} {...props} game={s.game} sound={sound}/>}
 </section>;
}
function CenturyTable({game:g,sound,...props}:Props&{game:Game;sound:ReturnType<typeof useCenturySound>}){
 const self=props.snapshot.self.playerId,players=props.snapshot.room.players,me=g.playerStates.find(p=>p.playerId===self)!;
 const [draft,setDraft]=useState(emptyCenturyDraft),[flight,setFlight]=useState(false),[message,setMessage]=useState<string|null>(null),[retry,setRetry]=useState<CenturyClientCommand|null>(null);
 const scope=`${g.gameId}:${g.gameRevision}:${g.phase}`,scopeRef=useRef(scope),commandRef=useRef<CenturyClientCommand|null>(null),mounted=useRef(true),dialog=useRef<HTMLDialogElement|null>(null);
 scopeRef.current=scope;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{setDraft(emptyCenturyDraft());setRetry(null);setMessage(null);commandRef.current=null;setFlight(false);},[scope]);
 const selected=draft.cardId!==null||draft.mode==='REST';
 useEffect(()=>{if(selected){if(dialog.current&&!dialog.current.open)dialog.current.showModal();}else dialog.current?.close();},[selected]);
 const canAct=g.phase==='PLAYING'&&g.activePlayerId===self&&props.connected&&!props.pending&&!flight&&retry===null;
 const preview=g.phase==='PLAYING'?previewCentury(g,draft):null;
 const name=(id:string)=>players.find(p=>p.playerId===id)?.nickname??'상인';
 const chosen=draft.mode==='HAND'?g.privateState.hand.find(c=>c.cardId===draft.cardId):null;
 const marketIndex=g.market.findIndex(m=>m.card.cardId===draft.cardId);
 const bonus=(index:number)=>index===0&&g.gold>0?'금화 +3점':(index===1&&g.gold>0||index===0&&g.gold===0)&&g.silver>0?'은화 +1점':'';
 function choose(mode:CenturyDraft['mode'],cardId:CenturyDraft['cardId']){if(!canAct)return;const d=emptyCenturyDraft();d.mode=mode;d.cardId=cardId;
  if(mode==='ACQUIRE'){const left=g.market.findIndex(m=>m.card.cardId===cardId),available=[...me.spices];for(let i=0;i<left;i++){const color=CENTURY_COLORS.find(c=>available[c]!>0);if(color===undefined){d.payment.push(0);}else{available[color]!--;d.payment.push(color);}}}
  setDraft(d);setMessage(null);sound.play('PICK');
 }
 function update(fn:(d:CenturyDraft)=>CenturyDraft){setDraft(d=>({...fn(d),returned:[0,0,0,0]}));sound.play('PICK');}
 async function send(c:CenturyClientCommand){if(commandRef.current!==null||!props.connected)return;commandRef.current=c;setFlight(true);setMessage(null);const sentScope=scope;
  try{await props.onCommand(c);if(mounted.current&&scopeRef.current===sentScope){setRetry(null);setDraft(emptyCenturyDraft());}}
  catch(error){if(mounted.current&&scopeRef.current===sentScope){if(error instanceof CenturyCommandRejected){setRetry(null);setMessage(error.message);sound.play('ERROR');}else{setRetry(c);setMessage('응답을 확인하지 못했습니다. 같은 요청으로 결과를 재확인하세요.');}}}
  finally{if(mounted.current&&commandRef.current===c){commandRef.current=null;setFlight(false);}}
 }
 function submit(action:CenturyAction){if(g.phase!=='PLAYING'||!canAct)return;void send({kind:'century:act',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload:action});}
 const starterIndex=g.playerStates.findIndex(p=>p.playerId===g.startingPlayerId),ordered=[...g.playerStates.slice(starterIndex),...g.playerStates.slice(0,starterIndex)];
 return <>
  <div className={`ct-turn-banner ${g.phase==='PLAYING'&&g.activePlayerId===self?'ct-my-turn':''}`} role="status"><strong>{g.phase==='FINISHED'?'교역 종료':g.activePlayerId===self?'나의 차례':`${name(g.activePlayerId)}의 차례`}</strong><span>{g.round}라운드 · {g.finalRound?'마지막 라운드':`목표 ${g.targetCount}장`}</span>{g.phase==='PLAYING'&&players.find(p=>p.playerId===g.activePlayerId)?.connectionStatus==='OFFLINE'?<span>재접속을 기다리고 있습니다</span>:null}</div>
  <div className="ct-players">{ordered.map((p,index)=><details key={p.playerId} className={`ct-player ${g.phase==='PLAYING'&&g.activePlayerId===p.playerId?'ct-active-player':''}`}><summary><span className="ct-player-name"><b>{name(p.playerId)}{p.playerId===self?' · 나':''}</b><small>{index===0?'♛ 선공':`${index+1}번째`}</small></span><Spices values={p.spices} all/><span className="ct-player-stats">목표 {p.pointCount}/{g.targetCount} · 손패 {p.handCount} · 사용 {p.played.length}</span><span className="ct-player-stats">금화 {p.gold} · 은화 {p.silver}{players.find(r=>r.playerId===p.playerId)?.connectionStatus==='OFFLINE'?' · 오프라인':''}</span></summary><div className="ct-played-list">{p.played.length?p.played.map(c=><span key={c.cardId}>{centuryCardText(c)}</span>):<span>사용한 카드 없음</span>}</div></details>)}</div>
  {g.phase==='FINISHED'?<section className="ct-results"><span className="ct-eyebrow">THE JOURNEY'S END</span><h2>{g.result.reason==='CANCELLED'?'게임이 취소되었습니다':`${name(g.result.winnerPlayerIds[0]!)}의 상단이 승리했습니다`}</h2><div className="ct-score-scroll"><table><thead><tr><th>상인</th><th>카드</th><th>동전</th><th>향신료</th><th>합계</th></tr></thead><tbody>{g.result.scores.map(p=><tr key={p.playerId}><th>{name(p.playerId)}</th><td>{p.cardPoints}</td><td>{p.coinPoints}</td><td>{p.spicePoints}</td><td><b>{p.total}</b></td></tr>)}</tbody></table></div>{players.find(p=>p.playerId===self)?.isHost?<button className="ct-primary" disabled={!props.connected||props.pending} onClick={props.onRematch}>같은 방에서 다시 하기</button>:<p>방장이 다음 게임을 선택할 수 있습니다.</p>}</section>:null}
  <section className="ct-market-section" aria-label="점수 카드 시장"><div className="ct-section-title"><h2><small>THE DESTINATIONS</small>점수 카드</h2><span>금화 {g.gold} · 은화 {g.silver} · 덱 {g.pointDeckCount}장</span></div><div className="ct-market-scroll" tabIndex={0} aria-label="점수 카드 가로 목록"><div className="ct-point-row">{g.pointMarket.map((c,i)=><PointCard key={c.cardId} card={c} bonus={bonus(i)} disabled={!canAct} selected={draft.mode==='CLAIM'&&draft.cardId===c.cardId} onClick={()=>choose('CLAIM',c.cardId)}/>)}</div></div></section>
  <section className="ct-market-section" aria-label="상인 카드 시장"><div className="ct-section-title"><h2><small>THE SPICE BAZAAR</small>상인 시장</h2><span>왼쪽 카드마다 1개 지불 · 덱 {g.merchantDeckCount}장</span></div><div className="ct-market-scroll" tabIndex={0} aria-label="상인 시장 왼쪽부터 순서대로"><div className="ct-merchant-row">{g.market.map((m,i)=><div className="ct-market-slot" key={m.card.cardId}><div className="ct-slot-cost"><b>{i+1}</b><span>{i===0?'무료':`향신료 ${i}개`}</span></div><Merchant card={m.card} selected={draft.mode==='ACQUIRE'&&draft.cardId===m.card.cardId} disabled={!canAct} onClick={()=>choose('ACQUIRE',m.card.cardId)}/><div className="ct-deposit"><small>함께 받는 자원</small><Spices values={m.spices}/></div></div>)}</div></div></section>
  {g.feedback?<div className="ct-feedback" key={`${g.gameId}:${g.gameRevision}`} role="status"><strong>{name(g.feedback.playerId)} · {CENTURY_ACTION_LABELS[g.feedback.kind]}</strong><span>지불 <Spices values={g.feedback.spent}/></span><span>획득 <Spices values={g.feedback.gained}/></span>{centurySum(g.feedback.returned)>0?<span>반환 <Spices values={g.feedback.returned}/></span>:null}</div>:null}
  <section className="ct-hand-section"><div className="ct-section-title"><h2><small>YOUR CARAVAN</small>내 상단</h2><span>향신료 {centurySum(me.spices)} / 10개</span></div><div className="ct-own-resources"><Spices values={me.spices} all/><button className="ct-rest" type="button" disabled={!canAct} onClick={()=>choose('REST',null)}>휴식 · {me.played.length}장 회수</button></div><div className="ct-hand">{g.privateState.hand.map(c=><Merchant key={c.cardId} card={c} disabled={!canAct} selected={draft.mode==='HAND'&&draft.cardId===c.cardId} onClick={()=>choose('HAND',c.cardId)}/>)}{!g.privateState.hand.length?<p>손패가 없습니다. 휴식으로 사용한 카드를 회수하세요.</p>:null}</div><details className="ct-own-points"><summary>내 획득 점수 카드 · {g.privateState.points.reduce((n,c)=>n+c.points,0)}점</summary><div className="ct-mini-points">{g.privateState.points.map(c=><span key={c.cardId}><b>{c.points}점</b><Spices values={c.cost}/></span>)}{!g.privateState.points.length?<p>아직 획득한 점수 카드가 없습니다.</p>:null}</div><p>상대의 획득 점수 카드 내용은 게임이 끝날 때까지 비공개입니다.</p></details><details><summary>내 사용한 카드 {me.played.length}장</summary><div className="ct-played-list">{me.played.map(c=><span key={c.cardId}>{centuryCardText(c)}</span>)}</div></details></section>
  <dialog className="ct-dialog" ref={dialog} aria-labelledby="ct-action-title" onCancel={e=>{if(flight||retry)e.preventDefault();else setDraft(emptyCenturyDraft());}}>
   <div className="ct-dialog-heading"><h2 id="ct-action-title">{draft.mode==='REST'?'휴식':draft.mode==='ACQUIRE'?'상인 카드 가져오기':draft.mode==='CLAIM'?'점수 카드 획득':chosen?CENTURY_ACTION_LABELS[chosen.kind]:'행동 선택'}</h2><button type="button" disabled={flight||retry!==null} onClick={()=>setDraft(emptyCenturyDraft())} aria-label="선택 취소하고 닫기">닫기</button></div>
   {chosen?<p className="ct-chosen-effect">{centuryCardText(chosen)}</p>:null}
   {draft.mode==='REST'?<p>사용한 카드 {me.played.length}장을 손패로 회수하고 차례를 마칩니다.</p>:null}
   {chosen?.kind==='TRADE'?<div className="ct-stepper"><span>교환 횟수</span><button type="button" disabled={!canAct||draft.times<=1} onClick={()=>update(d=>({...d,times:d.times-1}))}>−</button><b>{draft.times}회</b><button type="button" disabled={!canAct||draft.times>=10||CENTURY_COLORS.some(i=>chosen.cost[i]*(draft.times+1)>me.spices[i])} onClick={()=>update(d=>({...d,times:d.times+1}))}>+</button></div>:null}
   {chosen?.kind==='UPGRADE'?<div className="ct-upgrade-controls"><p>최대 {chosen.steps}단계 · 현재 {draft.upgrades.length}단계 선택</p><div className="ct-color-options">{([0,1,2] as const).map(i=><button key={i} type="button" disabled={!canAct||draft.upgrades.length>=chosen.steps||(preview?.beforeReturn[i]??0)<1} onClick={()=>update(d=>({...d,upgrades:[...d.upgrades,i]}))}>{CENTURY_LABELS[i]} → {CENTURY_LABELS[i+1]}</button>)}</div><p>{draft.upgrades.map(i=>`${CENTURY_LABELS[i]}→${CENTURY_LABELS[i+1]}`).join(' · ')||'선택한 업그레이드 없음'}</p><button type="button" disabled={!canAct||!draft.upgrades.length} onClick={()=>update(d=>({...d,upgrades:d.upgrades.slice(0,-1)}))}>한 단계 되돌리기</button></div>:null}
   {draft.mode==='ACQUIRE'?<div className="ct-payments"><p>{marketIndex===0?'첫 번째 카드는 무료입니다.':'왼쪽 각 카드에 놓을 향신료를 확인하세요.'}</p>{g.market.slice(0,Math.max(0,marketIndex)).map((m,i)=><label key={m.card.cardId}><span>{i+1}번 카드 · {centuryCardText(m.card)}</span><select aria-label={`${i+1}번 카드 지불 향신료`} disabled={!canAct} value={draft.payment[i]??''} onChange={e=>{const n=Number(e.target.value),color=CENTURY_COLORS.find(c=>c===n);if(color!==undefined)update(d=>{const payment=[...d.payment];payment[i]=color;return {...d,payment};});}}><option value="" disabled>선택</option>{CENTURY_COLORS.map(c=><option value={c} key={c}>{CENTURY_LABELS[c]}</option>)}</select></label>)}</div>:null}
   {preview?<><div className="ct-preview"><strong>실행 전 → 실행 후</strong><div>{CENTURY_COLORS.map(i=><span key={i} className={`ct-spice ct-spice-${i}`}><i aria-hidden="true">{['●','◆','▲','■'][i]}</i>{CENTURY_LABELS[i]} <b>{preview.before[i]} → {preview.after[i]}</b></span>)}</div><span>최종 {centurySum(preview.after)} / 10개 {preview.coin&&` · ${preview.coin}`}</span></div>{preview.excess>0?<fieldset className="ct-returns"><legend>초과 {preview.excess}개 반환 · 선택 {centurySum(draft.returned)}개</legend>{CENTURY_COLORS.map(i=><div className="ct-return-row" key={i}><span>{CENTURY_LABELS[i]}</span><button type="button" aria-label={`${CENTURY_LABELS[i]} 반환 줄이기`} disabled={!canAct||draft.returned[i]===0} onClick={()=>setDraft(d=>{const returned:CenturySpices=[...d.returned];returned[i]--;return {...d,returned};})}>−</button><b>{draft.returned[i]}</b><button type="button" aria-label={`${CENTURY_LABELS[i]} 반환 늘리기`} disabled={!canAct||draft.returned[i]>=preview.beforeReturn[i]||centurySum(draft.returned)>=preview.excess} onClick={()=>setDraft(d=>{const returned:CenturySpices=[...d.returned];returned[i]++;return {...d,returned};})}>+</button></div>)}</fieldset>:null}<p className="ct-validation" role="status">{preview.reason||'이 행동을 확정하면 차례가 끝납니다.'}</p></>:null}
   {message?<p className="ct-error" role="alert">{message}</p>:null}
   <div className="ct-dialog-footer">{retry?<button className="ct-primary" disabled={flight||!props.connected} onClick={()=>void send(retry)}>같은 요청 결과 재확인</button>:<button className="ct-primary" disabled={!canAct||!preview?.action} onClick={()=>{if(preview?.action)submit(preview.action);}}>{flight?'결과 확인 중…':'행동 확정'}</button>}</div>
  </dialog>
 </>;
}
