/** Independently authored Korean prompts; not sourced from a commercial word list. */
export const DRAW_PROMPTS = Object.freeze([
  { id: "DR-EASY-001", text: "사과", difficulty: "EASY" as const },
  { id: "DR-EASY-002", text: "바나나", difficulty: "EASY" as const },
  { id: "DR-EASY-003", text: "수박", difficulty: "EASY" as const },
  { id: "DR-EASY-004", text: "딸기", difficulty: "EASY" as const },
  { id: "DR-EASY-005", text: "포도", difficulty: "EASY" as const },
  { id: "DR-EASY-006", text: "귤", difficulty: "EASY" as const },
  { id: "DR-EASY-007", text: "복숭아", difficulty: "EASY" as const },
  { id: "DR-EASY-008", text: "파인애플", difficulty: "EASY" as const },
  { id: "DR-EASY-009", text: "레몬", difficulty: "EASY" as const },
  { id: "DR-EASY-010", text: "배", difficulty: "EASY" as const },
  { id: "DR-EASY-011", text: "당근", difficulty: "EASY" as const },
  { id: "DR-EASY-012", text: "오이", difficulty: "EASY" as const },
  { id: "DR-EASY-013", text: "호박", difficulty: "EASY" as const },
  { id: "DR-EASY-014", text: "가지", difficulty: "EASY" as const },
  { id: "DR-EASY-015", text: "감자", difficulty: "EASY" as const },
  { id: "DR-EASY-016", text: "고구마", difficulty: "EASY" as const },
  { id: "DR-EASY-017", text: "옥수수", difficulty: "EASY" as const },
  { id: "DR-EASY-018", text: "버섯", difficulty: "EASY" as const },
  { id: "DR-EASY-019", text: "브로콜리", difficulty: "EASY" as const },
  { id: "DR-EASY-020", text: "양파", difficulty: "EASY" as const },
  { id: "DR-EASY-021", text: "김밥", difficulty: "EASY" as const },
  { id: "DR-EASY-022", text: "떡볶이", difficulty: "EASY" as const },
  { id: "DR-EASY-023", text: "국수", difficulty: "EASY" as const },
  { id: "DR-EASY-024", text: "만두", difficulty: "EASY" as const },
  { id: "DR-EASY-025", text: "붕어빵", difficulty: "EASY" as const },
  { id: "DR-EASY-026", text: "호떡", difficulty: "EASY" as const },
  { id: "DR-EASY-027", text: "아이스크림", difficulty: "EASY" as const },
  { id: "DR-EASY-028", text: "케이크", difficulty: "EASY" as const },
  { id: "DR-EASY-029", text: "샌드위치", difficulty: "EASY" as const },
  { id: "DR-EASY-030", text: "피자", difficulty: "EASY" as const },
  { id: "DR-EASY-031", text: "우유", difficulty: "EASY" as const },
  { id: "DR-EASY-032", text: "주전자", difficulty: "EASY" as const },
  { id: "DR-EASY-033", text: "컵", difficulty: "EASY" as const },
  { id: "DR-EASY-034", text: "접시", difficulty: "EASY" as const },
  { id: "DR-EASY-035", text: "숟가락", difficulty: "EASY" as const },
  { id: "DR-EASY-036", text: "포크", difficulty: "EASY" as const },
  { id: "DR-EASY-037", text: "젓가락", difficulty: "EASY" as const },
  { id: "DR-EASY-038", text: "냄비", difficulty: "EASY" as const },
  { id: "DR-EASY-039", text: "프라이팬", difficulty: "EASY" as const },
  { id: "DR-EASY-040", text: "국자", difficulty: "EASY" as const },
  { id: "DR-EASY-041", text: "고양이", difficulty: "EASY" as const },
  { id: "DR-EASY-042", text: "강아지", difficulty: "EASY" as const },
  { id: "DR-EASY-043", text: "토끼", difficulty: "EASY" as const },
  { id: "DR-EASY-044", text: "거북이", difficulty: "EASY" as const },
  { id: "DR-EASY-045", text: "코끼리", difficulty: "EASY" as const },
  { id: "DR-EASY-046", text: "기린", difficulty: "EASY" as const },
  { id: "DR-EASY-047", text: "사자", difficulty: "EASY" as const },
  { id: "DR-EASY-048", text: "호랑이", difficulty: "EASY" as const },
  { id: "DR-EASY-049", text: "얼룩말", difficulty: "EASY" as const },
  { id: "DR-EASY-050", text: "하마", difficulty: "EASY" as const },
  { id: "DR-EASY-051", text: "곰", difficulty: "EASY" as const },
  { id: "DR-EASY-052", text: "여우", difficulty: "EASY" as const },
  { id: "DR-EASY-053", text: "다람쥐", difficulty: "EASY" as const },
  { id: "DR-EASY-054", text: "고슴도치", difficulty: "EASY" as const },
  { id: "DR-EASY-055", text: "판다", difficulty: "EASY" as const },
  { id: "DR-EASY-056", text: "코알라", difficulty: "EASY" as const },
  { id: "DR-EASY-057", text: "캥거루", difficulty: "EASY" as const },
  { id: "DR-EASY-058", text: "원숭이", difficulty: "EASY" as const },
  { id: "DR-EASY-059", text: "돼지", difficulty: "EASY" as const },
  { id: "DR-EASY-060", text: "양", difficulty: "EASY" as const },
  { id: "DR-EASY-061", text: "닭", difficulty: "EASY" as const },
  { id: "DR-EASY-062", text: "오리", difficulty: "EASY" as const },
  { id: "DR-EASY-063", text: "펭귄", difficulty: "EASY" as const },
  { id: "DR-EASY-064", text: "부엉이", difficulty: "EASY" as const },
  { id: "DR-EASY-065", text: "앵무새", difficulty: "EASY" as const },
  { id: "DR-EASY-066", text: "독수리", difficulty: "EASY" as const },
  { id: "DR-EASY-067", text: "참새", difficulty: "EASY" as const },
  { id: "DR-EASY-068", text: "백조", difficulty: "EASY" as const },
  { id: "DR-EASY-069", text: "공작", difficulty: "EASY" as const },
  { id: "DR-EASY-070", text: "타조", difficulty: "EASY" as const },
  { id: "DR-EASY-071", text: "물고기", difficulty: "EASY" as const },
  { id: "DR-EASY-072", text: "상어", difficulty: "EASY" as const },
  { id: "DR-EASY-073", text: "고래", difficulty: "EASY" as const },
  { id: "DR-EASY-074", text: "돌고래", difficulty: "EASY" as const },
  { id: "DR-EASY-075", text: "문어", difficulty: "EASY" as const },
  { id: "DR-EASY-076", text: "오징어", difficulty: "EASY" as const },
  { id: "DR-EASY-077", text: "해파리", difficulty: "EASY" as const },
  { id: "DR-EASY-078", text: "게", difficulty: "EASY" as const },
  { id: "DR-EASY-079", text: "불가사리", difficulty: "EASY" as const },
  { id: "DR-EASY-080", text: "해마", difficulty: "EASY" as const },
  { id: "DR-EASY-081", text: "나비", difficulty: "EASY" as const },
  { id: "DR-EASY-082", text: "벌", difficulty: "EASY" as const },
  { id: "DR-EASY-083", text: "무당벌레", difficulty: "EASY" as const },
  { id: "DR-EASY-084", text: "개미", difficulty: "EASY" as const },
  { id: "DR-EASY-085", text: "잠자리", difficulty: "EASY" as const },
  { id: "DR-EASY-086", text: "달팽이", difficulty: "EASY" as const },
  { id: "DR-EASY-087", text: "메뚜기", difficulty: "EASY" as const },
  { id: "DR-EASY-088", text: "장수풍뎅이", difficulty: "EASY" as const },
  { id: "DR-EASY-089", text: "거미", difficulty: "EASY" as const },
  { id: "DR-EASY-090", text: "애벌레", difficulty: "EASY" as const },
  { id: "DR-EASY-091", text: "해바라기", difficulty: "EASY" as const },
  { id: "DR-EASY-092", text: "튤립", difficulty: "EASY" as const },
  { id: "DR-EASY-093", text: "장미", difficulty: "EASY" as const },
  { id: "DR-EASY-094", text: "선인장", difficulty: "EASY" as const },
  { id: "DR-EASY-095", text: "소나무", difficulty: "EASY" as const },
  { id: "DR-EASY-096", text: "야자수", difficulty: "EASY" as const },
  { id: "DR-EASY-097", text: "대나무", difficulty: "EASY" as const },
  { id: "DR-EASY-098", text: "네잎클로버", difficulty: "EASY" as const },
  { id: "DR-EASY-099", text: "민들레", difficulty: "EASY" as const },
  { id: "DR-EASY-100", text: "연꽃", difficulty: "EASY" as const },
  { id: "DR-EASY-101", text: "집", difficulty: "EASY" as const },
  { id: "DR-EASY-102", text: "학교", difficulty: "EASY" as const },
  { id: "DR-EASY-103", text: "병원", difficulty: "EASY" as const },
  { id: "DR-EASY-104", text: "도서관", difficulty: "EASY" as const },
  { id: "DR-EASY-105", text: "소방서", difficulty: "EASY" as const },
  { id: "DR-EASY-106", text: "경찰서", difficulty: "EASY" as const },
  { id: "DR-EASY-107", text: "빵집", difficulty: "EASY" as const },
  { id: "DR-EASY-108", text: "등대", difficulty: "EASY" as const },
  { id: "DR-EASY-109", text: "풍차", difficulty: "EASY" as const },
  { id: "DR-EASY-110", text: "성", difficulty: "EASY" as const },
  { id: "DR-EASY-111", text: "산", difficulty: "EASY" as const },
  { id: "DR-EASY-112", text: "섬", difficulty: "EASY" as const },
  { id: "DR-EASY-113", text: "폭포", difficulty: "EASY" as const },
  { id: "DR-EASY-114", text: "강", difficulty: "EASY" as const },
  { id: "DR-EASY-115", text: "동굴", difficulty: "EASY" as const },
  { id: "DR-EASY-116", text: "화산", difficulty: "EASY" as const },
  { id: "DR-EASY-117", text: "무지개", difficulty: "EASY" as const },
  { id: "DR-EASY-118", text: "구름", difficulty: "EASY" as const },
  { id: "DR-EASY-119", text: "눈사람", difficulty: "EASY" as const },
  { id: "DR-EASY-120", text: "눈꽃", difficulty: "EASY" as const },
  { id: "DR-EASY-121", text: "태양", difficulty: "EASY" as const },
  { id: "DR-EASY-122", text: "달", difficulty: "EASY" as const },
  { id: "DR-EASY-123", text: "별", difficulty: "EASY" as const },
  { id: "DR-EASY-124", text: "혜성", difficulty: "EASY" as const },
  { id: "DR-EASY-125", text: "지구", difficulty: "EASY" as const },
  { id: "DR-EASY-126", text: "토성", difficulty: "EASY" as const },
  { id: "DR-EASY-127", text: "우주선", difficulty: "EASY" as const },
  { id: "DR-EASY-128", text: "로켓", difficulty: "EASY" as const },
  { id: "DR-EASY-129", text: "망원경", difficulty: "EASY" as const },
  { id: "DR-EASY-130", text: "우주복", difficulty: "EASY" as const },
  { id: "DR-EASY-131", text: "자동차", difficulty: "EASY" as const },
  { id: "DR-EASY-132", text: "버스", difficulty: "EASY" as const },
  { id: "DR-EASY-133", text: "기차", difficulty: "EASY" as const },
  { id: "DR-EASY-134", text: "비행기", difficulty: "EASY" as const },
  { id: "DR-EASY-135", text: "돛단배", difficulty: "EASY" as const },
  { id: "DR-EASY-136", text: "자전거", difficulty: "EASY" as const },
  { id: "DR-EASY-137", text: "오토바이", difficulty: "EASY" as const },
  { id: "DR-EASY-138", text: "헬리콥터", difficulty: "EASY" as const },
  { id: "DR-EASY-139", text: "잠수함", difficulty: "EASY" as const },
  { id: "DR-EASY-140", text: "열기구", difficulty: "EASY" as const },
  { id: "DR-EASY-141", text: "연필", difficulty: "EASY" as const },
  { id: "DR-EASY-142", text: "지우개", difficulty: "EASY" as const },
  { id: "DR-EASY-143", text: "가위", difficulty: "EASY" as const },
  { id: "DR-EASY-144", text: "자", difficulty: "EASY" as const },
  { id: "DR-EASY-145", text: "공책", difficulty: "EASY" as const },
  { id: "DR-EASY-146", text: "책가방", difficulty: "EASY" as const },
  { id: "DR-EASY-147", text: "팔레트", difficulty: "EASY" as const },
  { id: "DR-EASY-148", text: "붓", difficulty: "EASY" as const },
  { id: "DR-EASY-149", text: "크레파스", difficulty: "EASY" as const },
  { id: "DR-EASY-150", text: "풀", difficulty: "EASY" as const },
  { id: "DR-EASY-151", text: "모자", difficulty: "EASY" as const },
  { id: "DR-EASY-152", text: "안경", difficulty: "EASY" as const },
  { id: "DR-EASY-153", text: "우산", difficulty: "EASY" as const },
  { id: "DR-EASY-154", text: "장화", difficulty: "EASY" as const },
  { id: "DR-EASY-155", text: "운동화", difficulty: "EASY" as const },
  { id: "DR-EASY-156", text: "장갑", difficulty: "EASY" as const },
  { id: "DR-EASY-157", text: "목도리", difficulty: "EASY" as const },
  { id: "DR-EASY-158", text: "양말", difficulty: "EASY" as const },
  { id: "DR-EASY-159", text: "넥타이", difficulty: "EASY" as const },
  { id: "DR-EASY-160", text: "시계", difficulty: "EASY" as const },
  { id: "DR-EASY-161", text: "침대", difficulty: "EASY" as const },
  { id: "DR-EASY-162", text: "의자", difficulty: "EASY" as const },
  { id: "DR-EASY-163", text: "탁자", difficulty: "EASY" as const },
  { id: "DR-EASY-164", text: "옷장", difficulty: "EASY" as const },
  { id: "DR-EASY-165", text: "거울", difficulty: "EASY" as const },
  { id: "DR-EASY-166", text: "전등", difficulty: "EASY" as const },
  { id: "DR-EASY-167", text: "선풍기", difficulty: "EASY" as const },
  { id: "DR-EASY-168", text: "텔레비전", difficulty: "EASY" as const },
  { id: "DR-EASY-169", text: "냉장고", difficulty: "EASY" as const },
  { id: "DR-EASY-170", text: "세탁기", difficulty: "EASY" as const },
  { id: "DR-EASY-171", text: "축구공", difficulty: "EASY" as const },
  { id: "DR-EASY-172", text: "야구방망이", difficulty: "EASY" as const },
  { id: "DR-EASY-173", text: "농구대", difficulty: "EASY" as const },
  { id: "DR-EASY-174", text: "배드민턴채", difficulty: "EASY" as const },
  { id: "DR-EASY-175", text: "스키", difficulty: "EASY" as const },
  { id: "DR-EASY-176", text: "스케이트", difficulty: "EASY" as const },
  { id: "DR-EASY-177", text: "줄넘기", difficulty: "EASY" as const },
  { id: "DR-EASY-178", text: "훌라후프", difficulty: "EASY" as const },
  { id: "DR-EASY-179", text: "트로피", difficulty: "EASY" as const },
  { id: "DR-EASY-180", text: "볼링핀", difficulty: "EASY" as const },
  { id: "DR-EASY-181", text: "기타", difficulty: "EASY" as const },
  { id: "DR-EASY-182", text: "피아노", difficulty: "EASY" as const },
  { id: "DR-EASY-183", text: "북", difficulty: "EASY" as const },
  { id: "DR-EASY-184", text: "트럼펫", difficulty: "EASY" as const },
  { id: "DR-EASY-185", text: "바이올린", difficulty: "EASY" as const },
  { id: "DR-EASY-186", text: "마이크", difficulty: "EASY" as const },
  { id: "DR-EASY-187", text: "헤드폰", difficulty: "EASY" as const },
  { id: "DR-EASY-188", text: "음표", difficulty: "EASY" as const },
  { id: "DR-EASY-189", text: "악보", difficulty: "EASY" as const },
  { id: "DR-EASY-190", text: "리코더", difficulty: "EASY" as const },
  { id: "DR-EASY-191", text: "열쇠", difficulty: "EASY" as const },
  { id: "DR-EASY-192", text: "자물쇠", difficulty: "EASY" as const },
  { id: "DR-EASY-193", text: "망치", difficulty: "EASY" as const },
  { id: "DR-EASY-194", text: "톱", difficulty: "EASY" as const },
  { id: "DR-EASY-195", text: "삽", difficulty: "EASY" as const },
  { id: "DR-EASY-196", text: "사다리", difficulty: "EASY" as const },
  { id: "DR-EASY-197", text: "나침반", difficulty: "EASY" as const },
  { id: "DR-EASY-198", text: "지도", difficulty: "EASY" as const },
  { id: "DR-EASY-199", text: "텐트", difficulty: "EASY" as const },
  { id: "DR-EASY-200", text: "손전등", difficulty: "EASY" as const },
  { id: "DR-NORMAL-001", text: "양치하는 아이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-002", text: "세수하는 고양이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-003", text: "머리를 말리는 사람", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-004", text: "신발끈 묶기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-005", text: "도시락 싸기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-006", text: "빨래 널기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-007", text: "이불 개기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-008", text: "창문 닦기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-009", text: "설거지하기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-010", text: "쓰레기 분리수거", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-011", text: "계단 오르기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-012", text: "엘리베이터 기다리기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-013", text: "버스 놓치기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-014", text: "횡단보도 건너기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-015", text: "택시 잡기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-016", text: "지하철에서 졸기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-017", text: "자전거 펑크", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-018", text: "주차 연습", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-019", text: "길 묻기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-020", text: "신호등 앞에서 멈추기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-021", text: "김장하는 가족", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-022", text: "계란 뒤집기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-023", text: "면발 늘리기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-024", text: "주스 짜기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-025", text: "쿠키 굽기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-026", text: "케이크 장식", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-027", text: "소금 쏟기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-028", text: "매운 음식 먹기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-029", text: "뜨거운 국 식히기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-030", text: "얼음 씹기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-031", text: "연 날리기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-032", text: "비눗방울 불기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-033", text: "모래성 쌓기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-034", text: "조개 줍기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-035", text: "물수제비 뜨기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-036", text: "돌탑 쌓기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-037", text: "숨바꼭질", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-038", text: "고무줄놀이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-039", text: "보물찾기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-040", text: "종이비행기 접기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-041", text: "공 던지는 투수", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-042", text: "골 넣는 선수", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-043", text: "줄다리기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-044", text: "달리기 출발선", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-045", text: "수영 출발", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-046", text: "높이뛰기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-047", text: "역기 들기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-048", text: "양궁 과녁", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-049", text: "스케이트보드 묘기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-050", text: "탁구 시합", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-051", text: "빵 반죽하는 제빵사", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-052", text: "머리 자르는 미용사", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-053", text: "꽃 다듬는 꽃집 주인", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-054", text: "그물을 던지는 어부", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-055", text: "밭 가는 농부", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-056", text: "사진 찍는 사진사", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-057", text: "벽 칠하는 화가", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-058", text: "교통 정리하는 경찰", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-059", text: "편지 배달하는 우체부", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-060", text: "진찰하는 의사", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-061", text: "책 읽는 곰", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-062", text: "낮잠 자는 사자", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-063", text: "나무 타는 판다", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-064", text: "목욕하는 코끼리", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-065", text: "풀 먹는 얼룩말", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-066", text: "하품하는 하마", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-067", text: "굴 파는 토끼", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-068", text: "도토리 숨기는 다람쥐", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-069", text: "공 굴리는 물개", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-070", text: "얼음 위의 펭귄", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-071", text: "새싹에 물 주기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-072", text: "화분 옮겨 심기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-073", text: "낙엽 쓸기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-074", text: "벚꽃 구경", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-075", text: "은행잎 책갈피", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-076", text: "나뭇가지 그네", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-077", text: "덩굴 타고 오르기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-078", text: "벌집 관찰", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-079", text: "반딧불이 찾기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-080", text: "철새 떼", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-081", text: "비 오는 운동장", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-082", text: "눈 내리는 골목", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-083", text: "안개 낀 다리", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-084", text: "노을 진 바다", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-085", text: "달빛 아래 호수", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-086", text: "천둥 치는 하늘", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-087", text: "바람에 날린 모자", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-088", text: "우박 맞은 자동차", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-089", text: "물웅덩이 뛰어넘기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-090", text: "서리 낀 창문", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-091", text: "텐트 치는 가족", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-092", text: "모닥불 앞 기타", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-093", text: "산 정상 깃발", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-094", text: "등산 가방", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-095", text: "강가의 낚싯대", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-096", text: "숲속 오두막", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-097", text: "캠핑 의자", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-098", text: "쌍안경으로 새 보기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-099", text: "해먹에서 낮잠", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-100", text: "별 보는 야영장", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-101", text: "풍선 파는 가게", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-102", text: "회전목마", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-103", text: "관람차 꼭대기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-104", text: "롤러코스터 출발", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-105", text: "솜사탕 먹기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-106", text: "범퍼카 충돌", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-107", text: "놀이공원 입구", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-108", text: "동물원 기린 우리", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-109", text: "수족관 터널", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-110", text: "박물관 공룡 뼈", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-111", text: "생일 촛불 끄기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-112", text: "선물 포장", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-113", text: "꽃다발 받기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-114", text: "졸업사진", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-115", text: "결혼식 행진", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-116", text: "명절 세배", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-117", text: "새해 해돋이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-118", text: "운동회 응원", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-119", text: "학예회 연극", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-120", text: "불꽃놀이 구경", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-121", text: "종이배 띄우기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-122", text: "뜨개질하는 할머니", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-123", text: "퍼즐 맞추기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-124", text: "블록 탑 쌓기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-125", text: "도자기 빚기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-126", text: "붓글씨 쓰기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-127", text: "우표 모으기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-128", text: "구슬 꿰기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-129", text: "스티커 붙이기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-130", text: "종이왕관 만들기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-131", text: "공항 수하물 벨트", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-132", text: "기차역 플랫폼", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-133", text: "항구의 크레인", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-134", text: "비행기 창가", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-135", text: "여권 검사", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-136", text: "여행 가방 끌기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-137", text: "지도를 거꾸로 보기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-138", text: "기념품 가게", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-139", text: "유람선 갑판", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-140", text: "등대 불빛", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-141", text: "냉장고 문 열기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-142", text: "리모컨 찾기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-143", text: "충전기 꽂기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-144", text: "고장 난 선풍기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-145", text: "울리는 알람", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-146", text: "넘친 욕조", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-147", text: "물 새는 수도꼭지", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-148", text: "막힌 싱크대", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-149", text: "꺼진 전구 바꾸기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-150", text: "로봇 청소기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-151", text: "카페에서 주문", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-152", text: "식당 대기 줄", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-153", text: "영화관 팝콘", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-154", text: "마트 계산대", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-155", text: "시장 저울", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-156", text: "옷가게 탈의실", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-157", text: "서점 진열대", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-158", text: "분실물 보관소", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-159", text: "동네 세탁소", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-160", text: "버스 정류장", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-161", text: "기지개 켜기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-162", text: "재채기 참기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-163", text: "딸꾹질하기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-164", text: "배꼽 잡고 웃기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-165", text: "발끝으로 걷기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-166", text: "한 발로 서기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-167", text: "벽에 기대기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-168", text: "거꾸로 물구나무", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-169", text: "졸음을 참기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-170", text: "손뼉 치기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-171", text: "장난감 기차", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-172", text: "태엽 인형", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-173", text: "저금통 동전", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-174", text: "자석 낚시", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-175", text: "팽이 돌리기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-176", text: "요요 묘기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-177", text: "마술사의 모자", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-178", text: "카드 쌓기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-179", text: "가면 만들기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-180", text: "보드게임 주사위", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-181", text: "달걀을 품는 닭", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-182", text: "웅덩이의 오리", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-183", text: "나뭇가지 위 부엉이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-184", text: "실뭉치와 고양이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-185", text: "원반 물어오는 강아지", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-186", text: "배추 위 애벌레", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-187", text: "꽃에 앉은 나비", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-188", text: "전깃줄 위 참새", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-189", text: "바위 위 도마뱀", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-190", text: "산호 속 물고기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-191", text: "의자에 걸린 가방", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-192", text: "책 사이의 꽃", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-193", text: "창가의 선인장", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-194", text: "문 앞 택배", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-195", text: "비어 있는 운동화", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-196", text: "거꾸로 쓴 안경", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-197", text: "옷걸이의 코트", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-198", text: "접힌 우산", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-199", text: "먼지 쌓인 피아노", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-200", text: "깨진 달걀 껍데기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-201", text: "다리 위 자전거", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-202", text: "옥상의 빨랫줄", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-203", text: "지붕 위 풍향계", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-204", text: "성벽의 시계탑", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-205", text: "골목의 벽화", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-206", text: "광장의 분수", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-207", text: "터널 입구", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-208", text: "숲속 나무다리", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-209", text: "언덕 위 풍차", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-210", text: "길가의 이정표", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-211", text: "소풍 돗자리", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-212", text: "도시락의 문어 소시지", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-213", text: "떨어진 아이스크림", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-214", text: "빵 부스러기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-215", text: "넘치는 팝콘", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-216", text: "반쪽 수박", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-217", text: "꼬치에 꽂힌 과일", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-218", text: "가득 찬 과자 봉지", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-219", text: "빨대로 거품 내기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-220", text: "초콜릿 분수", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-221", text: "스케치북 펼치기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-222", text: "합창단 지휘", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-223", text: "무대 커튼 열기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-224", text: "드럼 연주", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-225", text: "기타 줄 튕기기", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-226", text: "바이올린 조율", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-227", text: "노래방 마이크", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-228", text: "발레 연습", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-229", text: "박수 받는 배우", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-230", text: "거리의 초상화", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-231", text: "줄 선 개미", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-232", text: "씨앗 나르는 새", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-233", text: "물이 흐르는 수차", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-234", text: "눈 녹은 처마", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-235", text: "굴러가는 낙엽", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-236", text: "꽃가루 날리는 봄", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-237", text: "그늘 속 고양이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-238", text: "물 위 연잎", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-239", text: "조약돌 해변", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-240", text: "해 질 녘 그림자", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-241", text: "넘어진 책 더미", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-242", text: "잃어버린 양말 한 짝", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-243", text: "끊어진 목걸이", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-244", text: "너무 큰 모자", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-245", text: "짧아진 연필", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-246", text: "구멍 난 장갑", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-247", text: "엉킨 이어폰", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-248", text: "풀린 운동화 끈", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-249", text: "뒤집힌 장바구니", difficulty: "NORMAL" as const },
  { id: "DR-NORMAL-250", text: "비뚤어진 액자", difficulty: "NORMAL" as const },
  { id: "DR-HARD-001", text: "구름을 수확하는 농부", difficulty: "HARD" as const },
  { id: "DR-HARD-002", text: "달에 편지 보내는 토끼", difficulty: "HARD" as const },
  { id: "DR-HARD-003", text: "우산을 쓴 분수", difficulty: "HARD" as const },
  { id: "DR-HARD-004", text: "바다를 건너는 책장", difficulty: "HARD" as const },
  { id: "DR-HARD-005", text: "별을 닦는 청소부", difficulty: "HARD" as const },
  { id: "DR-HARD-006", text: "무지개를 짜는 재봉사", difficulty: "HARD" as const },
  { id: "DR-HARD-007", text: "모래시계 속 정원", difficulty: "HARD" as const },
  { id: "DR-HARD-008", text: "낙엽으로 만든 배", difficulty: "HARD" as const },
  { id: "DR-HARD-009", text: "파도 위의 도서관", difficulty: "HARD" as const },
  { id: "DR-HARD-010", text: "눈송이를 굽는 빵집", difficulty: "HARD" as const },
  { id: "DR-HARD-011", text: "하늘을 나는 우체통", difficulty: "HARD" as const },
  { id: "DR-HARD-012", text: "지붕을 들고 걷는 집", difficulty: "HARD" as const },
  { id: "DR-HARD-013", text: "나무 꼭대기 기차역", difficulty: "HARD" as const },
  { id: "DR-HARD-014", text: "뿌리로 춤추는 나무", difficulty: "HARD" as const },
  { id: "DR-HARD-015", text: "바람을 파는 상인", difficulty: "HARD" as const },
  { id: "DR-HARD-016", text: "빛을 담는 유리병", difficulty: "HARD" as const },
  { id: "DR-HARD-017", text: "그림자를 산책시키기", difficulty: "HARD" as const },
  { id: "DR-HARD-018", text: "산을 접는 종이접기", difficulty: "HARD" as const },
  { id: "DR-HARD-019", text: "해를 가리는 해바라기", difficulty: "HARD" as const },
  { id: "DR-HARD-020", text: "밤하늘의 빨랫줄", difficulty: "HARD" as const },
  { id: "DR-HARD-021", text: "책에서 자라는 숲", difficulty: "HARD" as const },
  { id: "DR-HARD-022", text: "소라껍데기 음악당", difficulty: "HARD" as const },
  { id: "DR-HARD-023", text: "연못 속 찻집", difficulty: "HARD" as const },
  { id: "DR-HARD-024", text: "성냥갑 속 도시", difficulty: "HARD" as const },
  { id: "DR-HARD-025", text: "찻잔을 타고 여행", difficulty: "HARD" as const },
  { id: "DR-HARD-026", text: "연필로 그리는 다리", difficulty: "HARD" as const },
  { id: "DR-HARD-027", text: "편지 봉투 속 바다", difficulty: "HARD" as const },
  { id: "DR-HARD-028", text: "시계 안의 운동장", difficulty: "HARD" as const },
  { id: "DR-HARD-029", text: "단추로 만든 행성", difficulty: "HARD" as const },
  { id: "DR-HARD-030", text: "신발 속 작은 마을", difficulty: "HARD" as const },
  { id: "DR-HARD-031", text: "시간을 배달하는 자전거", difficulty: "HARD" as const },
  { id: "DR-HARD-032", text: "어제를 찾는 탐정", difficulty: "HARD" as const },
  { id: "DR-HARD-033", text: "내일을 그리는 화가", difficulty: "HARD" as const },
  { id: "DR-HARD-034", text: "거꾸로 흐르는 폭포", difficulty: "HARD" as const },
  { id: "DR-HARD-035", text: "구름 계단 오르기", difficulty: "HARD" as const },
  { id: "DR-HARD-036", text: "달빛으로 짠 목도리", difficulty: "HARD" as const },
  { id: "DR-HARD-037", text: "별자리 낚시", difficulty: "HARD" as const },
  { id: "DR-HARD-038", text: "꿈을 담는 가방", difficulty: "HARD" as const },
  { id: "DR-HARD-039", text: "웃음을 파는 가게", difficulty: "HARD" as const },
  { id: "DR-HARD-040", text: "하품을 모으는 항아리", difficulty: "HARD" as const },
  { id: "DR-HARD-041", text: "수박 안의 수영장", difficulty: "HARD" as const },
  { id: "DR-HARD-042", text: "도넛 위의 관람차", difficulty: "HARD" as const },
  { id: "DR-HARD-043", text: "브로콜리 숲 탐험", difficulty: "HARD" as const },
  { id: "DR-HARD-044", text: "국수로 짠 그물", difficulty: "HARD" as const },
  { id: "DR-HARD-045", text: "당근 로켓 발사", difficulty: "HARD" as const },
  { id: "DR-HARD-046", text: "쿠키 벽돌 집", difficulty: "HARD" as const },
  { id: "DR-HARD-047", text: "우유 폭포", difficulty: "HARD" as const },
  { id: "DR-HARD-048", text: "젤리로 만든 의자", difficulty: "HARD" as const },
  { id: "DR-HARD-049", text: "아이스크림 산 등반", difficulty: "HARD" as const },
  { id: "DR-HARD-050", text: "팝콘 눈보라", difficulty: "HARD" as const },
  { id: "DR-HARD-051", text: "느림보 달팽이 택배", difficulty: "HARD" as const },
  { id: "DR-HARD-052", text: "스케이트 타는 선인장", difficulty: "HARD" as const },
  { id: "DR-HARD-053", text: "독서하는 문어 사서", difficulty: "HARD" as const },
  { id: "DR-HARD-054", text: "목도리 짜는 거미", difficulty: "HARD" as const },
  { id: "DR-HARD-055", text: "축구 심판 펭귄", difficulty: "HARD" as const },
  { id: "DR-HARD-056", text: "꽃다발 만드는 기린", difficulty: "HARD" as const },
  { id: "DR-HARD-057", text: "피아노 조율하는 생쥐", difficulty: "HARD" as const },
  { id: "DR-HARD-058", text: "구름 양을 모는 강아지", difficulty: "HARD" as const },
  { id: "DR-HARD-059", text: "전구를 갈아주는 반딧불이", difficulty: "HARD" as const },
  { id: "DR-HARD-060", text: "도토리 은행장 다람쥐", difficulty: "HARD" as const },
  { id: "DR-HARD-061", text: "거울 속 사람이 먼저 인사", difficulty: "HARD" as const },
  { id: "DR-HARD-062", text: "그림자끼리 가위바위보", difficulty: "HARD" as const },
  { id: "DR-HARD-063", text: "의자가 사람을 업기", difficulty: "HARD" as const },
  { id: "DR-HARD-064", text: "우산이 비를 피하기", difficulty: "HARD" as const },
  { id: "DR-HARD-065", text: "알람을 깨우는 사람", difficulty: "HARD" as const },
  { id: "DR-HARD-066", text: "양말이 신발 찾기", difficulty: "HARD" as const },
  { id: "DR-HARD-067", text: "지우개가 연필을 그리기", difficulty: "HARD" as const },
  { id: "DR-HARD-068", text: "책이 독자를 읽기", difficulty: "HARD" as const },
  { id: "DR-HARD-069", text: "문이 집을 두드리기", difficulty: "HARD" as const },
  { id: "DR-HARD-070", text: "지도 속에서 길 잃기", difficulty: "HARD" as const },
  { id: "DR-HARD-071", text: "발 없는 말이 천 리 가기", difficulty: "HARD" as const },
  { id: "DR-HARD-072", text: "티끌 모아 태산", difficulty: "HARD" as const },
  { id: "DR-HARD-073", text: "하늘의 별 따기", difficulty: "HARD" as const },
  { id: "DR-HARD-074", text: "우물 안 개구리", difficulty: "HARD" as const },
  { id: "DR-HARD-075", text: "꿩 대신 닭", difficulty: "HARD" as const },
  { id: "DR-HARD-076", text: "누워서 떡 먹기", difficulty: "HARD" as const },
  { id: "DR-HARD-077", text: "바늘 가는 데 실 가기", difficulty: "HARD" as const },
  { id: "DR-HARD-078", text: "그림의 떡", difficulty: "HARD" as const },
  { id: "DR-HARD-079", text: "소 잃고 외양간 고치기", difficulty: "HARD" as const },
  { id: "DR-HARD-080", text: "등잔 밑이 어둡기", difficulty: "HARD" as const },
  { id: "DR-HARD-081", text: "구름 위 이사", difficulty: "HARD" as const },
  { id: "DR-HARD-082", text: "달의 마지막 버스", difficulty: "HARD" as const },
  { id: "DR-HARD-083", text: "잠든 도시의 야간 배달", difficulty: "HARD" as const },
  { id: "DR-HARD-084", text: "해저 우체국", difficulty: "HARD" as const },
  { id: "DR-HARD-085", text: "공중에 뜬 운동장", difficulty: "HARD" as const },
  { id: "DR-HARD-086", text: "별똥별 정거장", difficulty: "HARD" as const },
  { id: "DR-HARD-087", text: "빙하 속 온실", difficulty: "HARD" as const },
  { id: "DR-HARD-088", text: "비밀 통로가 된 책장", difficulty: "HARD" as const },
  { id: "DR-HARD-089", text: "노을빛 지하철", difficulty: "HARD" as const },
  { id: "DR-HARD-090", text: "사막의 눈사람 축제", difficulty: "HARD" as const },
  { id: "DR-HARD-091", text: "연주하면 꽃이 피는 기타", difficulty: "HARD" as const },
  { id: "DR-HARD-092", text: "발자국마다 물고기", difficulty: "HARD" as const },
  { id: "DR-HARD-093", text: "걷는 만큼 자라는 신발", difficulty: "HARD" as const },
  { id: "DR-HARD-094", text: "접으면 작아지는 산", difficulty: "HARD" as const },
  { id: "DR-HARD-095", text: "웃으면 커지는 풍선", difficulty: "HARD" as const },
  { id: "DR-HARD-096", text: "비를 부르는 북", difficulty: "HARD" as const },
  { id: "DR-HARD-097", text: "달을 담은 손거울", difficulty: "HARD" as const },
  { id: "DR-HARD-098", text: "꿈으로 채운 베개", difficulty: "HARD" as const },
  { id: "DR-HARD-099", text: "끝없이 늘어나는 국수", difficulty: "HARD" as const },
  { id: "DR-HARD-100", text: "노래하는 나침반", difficulty: "HARD" as const },
  { id: "DR-HARD-101", text: "나무가 잎 대신 편지를 달기", difficulty: "HARD" as const },
  { id: "DR-HARD-102", text: "시계가 바늘 대신 당근 들기", difficulty: "HARD" as const },
  { id: "DR-HARD-103", text: "구름이 우산을 접기", difficulty: "HARD" as const },
  { id: "DR-HARD-104", text: "고래가 섬을 이고 가기", difficulty: "HARD" as const },
  { id: "DR-HARD-105", text: "파도가 인사하며 모자를 벗기", difficulty: "HARD" as const },
  { id: "DR-HARD-106", text: "별이 줄지어 등교하기", difficulty: "HARD" as const },
  { id: "DR-HARD-107", text: "숲이 여행 가방에 들어가기", difficulty: "HARD" as const },
  { id: "DR-HARD-108", text: "강이 길을 물어보기", difficulty: "HARD" as const },
  { id: "DR-HARD-109", text: "산이 기지개 켜기", difficulty: "HARD" as const },
  { id: "DR-HARD-110", text: "달이 초승달 빵 굽기", difficulty: "HARD" as const },
  { id: "DR-HARD-111", text: "바닥이 천장이 된 방", difficulty: "HARD" as const },
  { id: "DR-HARD-112", text: "소리가 색깔로 보이는 거리", difficulty: "HARD" as const },
  { id: "DR-HARD-113", text: "모든 문이 바다로 이어지는 집", difficulty: "HARD" as const },
  { id: "DR-HARD-114", text: "거대한 풀잎 아래 소풍", difficulty: "HARD" as const },
  { id: "DR-HARD-115", text: "손바닥만 한 기차 여행", difficulty: "HARD" as const },
  { id: "DR-HARD-116", text: "하루 동안 나무가 되기", difficulty: "HARD" as const },
  { id: "DR-HARD-117", text: "색을 잃은 무지개", difficulty: "HARD" as const },
  { id: "DR-HARD-118", text: "사진 밖으로 나온 폭포", difficulty: "HARD" as const },
  { id: "DR-HARD-119", text: "스스로 그려지는 지도", difficulty: "HARD" as const },
  { id: "DR-HARD-120", text: "눈 감으면 켜지는 등대", difficulty: "HARD" as const },
  { id: "DR-HARD-121", text: "선물 상자를 포장하는 선물 상자", difficulty: "HARD" as const },
  { id: "DR-HARD-122", text: "종이비행기 공항 관제탑", difficulty: "HARD" as const },
  { id: "DR-HARD-123", text: "떠다니는 빨래 섬", difficulty: "HARD" as const },
  { id: "DR-HARD-124", text: "컵 손잡이의 미끄럼틀", difficulty: "HARD" as const },
  { id: "DR-HARD-125", text: "오케스트라를 지휘하는 바람", difficulty: "HARD" as const },
  { id: "DR-HARD-126", text: "조개껍데기를 빌리는 달팽이", difficulty: "HARD" as const },
  { id: "DR-HARD-127", text: "나뭇잎으로 우산 만드는 개미", difficulty: "HARD" as const },
  { id: "DR-HARD-128", text: "무지개 다리 통행료", difficulty: "HARD" as const },
  { id: "DR-HARD-129", text: "별을 세다가 잠든 로봇", difficulty: "HARD" as const },
  { id: "DR-HARD-130", text: "책갈피를 찾는 책", difficulty: "HARD" as const },
  { id: "DR-HARD-131", text: "비 오는 날 구름 수리", difficulty: "HARD" as const },
  { id: "DR-HARD-132", text: "폭포를 거슬러 오르는 엘리베이터", difficulty: "HARD" as const },
  { id: "DR-HARD-133", text: "바다 밑 낙엽 청소", difficulty: "HARD" as const },
  { id: "DR-HARD-134", text: "밤을 접어 보관하기", difficulty: "HARD" as const },
  { id: "DR-HARD-135", text: "봄을 기다리는 눈사람", difficulty: "HARD" as const },
  { id: "DR-HARD-136", text: "여름을 냉장고에 넣기", difficulty: "HARD" as const },
  { id: "DR-HARD-137", text: "겨울 코트를 입은 태양", difficulty: "HARD" as const },
  { id: "DR-HARD-138", text: "가을을 배달하는 트럭", difficulty: "HARD" as const },
  { id: "DR-HARD-139", text: "달력에서 도망친 주말", difficulty: "HARD" as const },
  { id: "DR-HARD-140", text: "시계를 멈추려는 늦잠", difficulty: "HARD" as const },
  { id: "DR-HARD-141", text: "수평선을 재는 자", difficulty: "HARD" as const },
  { id: "DR-HARD-142", text: "바람 방향을 바꾸는 부채", difficulty: "HARD" as const },
  { id: "DR-HARD-143", text: "꽃향기로 만든 길", difficulty: "HARD" as const },
  { id: "DR-HARD-144", text: "구름 그림자 퍼즐", difficulty: "HARD" as const },
  { id: "DR-HARD-145", text: "별빛을 저축하는 저금통", difficulty: "HARD" as const },
  { id: "DR-HARD-146", text: "파도 머리 빗기", difficulty: "HARD" as const },
  { id: "DR-HARD-147", text: "비밀을 속삭이는 풍차", difficulty: "HARD" as const },
  { id: "DR-HARD-148", text: "노을을 포장하는 공방", difficulty: "HARD" as const },
  { id: "DR-HARD-149", text: "하늘색을 고르는 구름", difficulty: "HARD" as const },
  { id: "DR-HARD-150", text: "첫눈을 기다리는 우체통", difficulty: "HARD" as const },
]);
