export const CITY_EXPANDED_ROLES = [
  { id: 'ASSASSIN', rank: 1, name: '암살자', text: '역할 하나를 암살해 이번 라운드 차례를 건너뜁니다.' },
  { id: 'WITCH', rank: 1, name: '마녀', text: '자원을 얻은 뒤 다른 역할을 홀립니다. 대상이 자원을 얻으면 그 역할의 나머지 차례를 진행합니다.' },
  { id: 'MAGISTRATE', rank: 1, name: '치안판사', text: '역할 셋에 영장을 놓고 진짜 영장 대상의 첫 유료 건물을 몰수할 수 있습니다.' },
  { id: 'THIEF', rank: 2, name: '도둑', text: '역할 하나를 지목해 그 역할 차례 시작에 소유자의 금화를 가져옵니다.' },
  { id: 'SPY', rank: 2, name: '첩자', text: '상대와 종류를 지목합니다. 해당 손패 수만큼 금화를 빼앗고 카드를 뽑습니다.' },
  { id: 'BLACKMAILER', rank: 2, name: '협박범', text: '두 역할을 협박합니다. 대상은 금화 절반을 내거나 거절합니다. 진짜 협박 공개 시 전부 잃습니다.' },
  { id: 'MAGICIAN', rank: 3, name: '마술사', text: '상대와 손패 전부를 바꾸거나 자기 손패를 원하는 만큼 교체합니다.' },
  { id: 'WIZARD', rank: 3, name: '마법사', text: '상대 손패를 보고 한 장을 가져오거나 즉시 추가 건설합니다. 같은 건물을 지을 수 있습니다.' },
  { id: 'SEER', rank: 3, name: '예언자', text: '각 상대에게 무작위 한 장을 받은 뒤 각각 한 장을 돌려줍니다. 최대 2채 건설.' },
  { id: 'KING', rank: 4, name: '왕', text: '왕관을 받습니다. 시정 건물마다 금화 1개를 얻습니다.' },
  { id: 'EMPEROR', rank: 4, name: '황제', text: '시정 건물마다 금화 1개. 자신과 현재 소유자를 제외한 상대에게 왕관을 주고 금화 또는 카드 1개를 받습니다.' },
  { id: 'PATRICIAN', rank: 4, name: '대공', text: '왕관을 받습니다. 시정 건물마다 카드 1장을 얻습니다.' },
  { id: 'BISHOP', rank: 5, name: '주교', text: '문화 건물마다 금화 1개. 자신의 도시는 8번 역할에게 보호됩니다.' },
  { id: 'ABBOT', rank: 5, name: '수도원장', text: '문화 건물 수만큼 금화와 카드를 나눠 받습니다. 자신보다 부자인 가장 부유한 상대에게 금화 1개를 받습니다.' },
  { id: 'CARDINAL', rank: 5, name: '추기경', text: '문화 건물마다 카드 1장. 건설비 부족분만큼 다른 사람에게 손패를 주고 금화를 받습니다.' },
  { id: 'MERCHANT', rank: 6, name: '상인', text: '추가 금화 1개와 교역 건물마다 금화 1개를 얻습니다.' },
  { id: 'ALCHEMIST', rank: 6, name: '연금술사', text: '차례 끝에 건설에 실제 사용한 금화를 돌려받습니다.' },
  { id: 'TRADER', rank: 6, name: '교역상', text: '교역 건물마다 금화 1개. 교역 건설은 건설 횟수에 포함하지 않습니다.' },
  { id: 'ARCHITECT', rank: 7, name: '건축가', text: '추가 카드 2장을 얻고 최대 3채 건설합니다.' },
  { id: 'NAVIGATOR', rank: 7, name: '항해사', text: '추가 금화 4개 또는 카드 4장. 건물을 지을 수 없습니다.' },
  { id: 'SCHOLAR', rank: 7, name: '학자', text: '카드 7장 중 1장을 갖고 나머지를 섞어 돌려놓습니다. 최대 2채 건설.' },
  { id: 'WARLORD', rank: 8, name: '장군', text: '수비 건물마다 금화 1개. 비용보다 금화 1개 적게 내고 건물 하나를 파괴합니다.' },
  { id: 'DIPLOMAT', rank: 8, name: '외교관', text: '수비 건물마다 금화 1개. 상대와 건물을 바꾸며 상대 건물이 더 비싸면 차액을 줍니다.' },
  { id: 'MARSHAL', rank: 8, name: '육군대장', text: '수비 건물마다 금화 1개. 비용 3 이하의 상대 건물을 비용만큼 지불해 가져옵니다.' },
  { id: 'QUEEN', rank: 9, name: '왕비', text: '4번 역할 소유자가 옆자리라면 금화 3개. 5인 이상에서 사용합니다.' },
  { id: 'ARTIST', rank: 9, name: '예술가', text: '건물당 금화 1개로 최대 2채를 장식합니다. 장식된 건물은 비용과 점수가 1 증가합니다.' },
  { id: 'TAX_COLLECTOR', rank: 9, name: '세리', text: '다른 역할이 건설 후 내는 세금을 모아 가져옵니다.' },
] as const;
export type CityJobId = (typeof CITY_EXPANDED_ROLES)[number]['id'];
export const CITY_SPECIAL_BUILDINGS = [
  { templateId: 'CB-SP-01', effect: 'ARMORY', name: '병기고', cost: 3, text: '이 건물을 파괴해 완성되지 않은 도시의 다른 건물 1채를 파괴합니다.' },
  { templateId: 'CB-SP-02', effect: 'BASILICA', name: '대성당', cost: 4, text: '종료 시 비용이 홀수인 자기 건물마다 +1점.' },
  { templateId: 'CB-SP-03', effect: 'CAPITOL', name: '의사당', cost: 5, text: '종료 시 같은 종류의 건물이 3채 이상 있으면 +3점.' },
  { templateId: 'CB-SP-04', effect: 'DRAGON_GATE', name: '용의 문', cost: 6, text: '종료 시 +2점.' },
  { templateId: 'CB-SP-05', effect: 'FACTORY', name: '공장', cost: 5, text: '다른 특수 건물을 건설할 때 비용 -1.' },
  { templateId: 'CB-SP-06', effect: 'FRAMEWORK', name: '골조', cost: 3, text: '이 건물을 파괴해 다른 건물 1채의 건설비를 대신합니다.' },
  { templateId: 'CB-SP-07', effect: 'GOLD_MINE', name: '금광', cost: 6, text: '기본 자원 획득에서 금화를 선택하면 금화 1개 추가.' },
  { templateId: 'CB-SP-08', effect: 'GREAT_WALL', name: '대성벽', cost: 6, text: '8번 역할이 내 다른 건물에 능력을 쓰려면 금화 1개를 추가로 내야 합니다.' },
  { templateId: 'CB-SP-09', effect: 'HAUNTED_QUARTER', name: '유령 지구', cost: 2, text: '종료 시 원하는 일반 건물 종류 하나로 취급할 수 있습니다.' },
  { templateId: 'CB-SP-10', effect: 'IMPERIAL_TREASURY', name: '황실 금고', cost: 5, text: '종료 시 남은 금화마다 +1점.' },
  { templateId: 'CB-SP-11', effect: 'IVORY_TOWER', name: '상아탑', cost: 5, text: '도시의 유일한 특수 건물이 이것뿐이면 종료 시 +5점.' },
  { templateId: 'CB-SP-12', effect: 'KEEP', name: '성채', cost: 3, text: '8번 역할의 능력 대상이 될 수 없습니다.' },
  { templateId: 'CB-SP-13', effect: 'LABORATORY', name: '연구소', cost: 5, text: '차례당 한 번 손패 1장을 버리고 금화 2개를 얻습니다.' },
  { templateId: 'CB-SP-14', effect: 'LIBRARY', name: '도서관', cost: 6, text: '기본 카드 획득에서 뽑은 카드를 모두 가집니다.' },
  { templateId: 'CB-SP-15', effect: 'MAP_ROOM', name: '지도실', cost: 5, text: '종료 시 남은 손패마다 +1점.' },
  { templateId: 'CB-SP-16', effect: 'MONUMENT', name: '기념비', cost: 4, text: '이미 5채 이상이면 건설할 수 없습니다. 도시 완성에서는 2채로 셉니다.' },
  { templateId: 'CB-SP-17', effect: 'MUSEUM', name: '박물관', cost: 4, text: '차례당 한 번 손패 1장을 밑에 보관합니다. 종료 시 보관 카드마다 +1점.' },
  { templateId: 'CB-SP-18', effect: 'NECROPOLIS', name: '묘지', cost: 5, text: '금화 대신 자기 건물 1채를 파괴해 건설할 수 있습니다.' },
  { templateId: 'CB-SP-19', effect: 'OBSERVATORY', name: '천문대', cost: 4, text: '기본 카드 획득에서 3장을 보고 1장을 고릅니다.' },
  { templateId: 'CB-SP-20', effect: 'PARK', name: '공원', cost: 6, text: '차례 끝에 손패가 없으면 카드 2장을 얻습니다.' },
  { templateId: 'CB-SP-21', effect: 'POOR_HOUSE', name: '구빈원', cost: 4, text: '차례 끝에 금화가 없으면 금화 1개를 얻습니다.' },
  { templateId: 'CB-SP-22', effect: 'QUARRY', name: '채석장', cost: 5, text: '자기 도시에 같은 이름의 건물을 중복 건설할 수 있습니다.' },
  { templateId: 'CB-SP-23', effect: 'SCHOOL_OF_MAGIC', name: '마법 학교', cost: 6, text: '역할의 종류별 수입 계산에서 원하는 건물 종류 하나로 취급합니다.' },
  { templateId: 'CB-SP-24', effect: 'SECRET_VAULT', name: '비밀 금고', cost: 0, text: '건설할 수 없습니다. 종료까지 손에 들고 있으면 공개하고 +3점.' },
  { templateId: 'CB-SP-25', effect: 'SMITHY', name: '대장간', cost: 5, text: '차례당 한 번 금화 2개를 내고 카드 3장을 얻습니다.' },
  { templateId: 'CB-SP-26', effect: 'STABLES', name: '마구간', cost: 2, text: '이 건물의 건설은 건설 횟수 제한에 포함하지 않습니다.' },
  { templateId: 'CB-SP-27', effect: 'STATUE', name: '동상', cost: 3, text: '종료 시 왕관을 가지고 있으면 +5점.' },
  { templateId: 'CB-SP-28', effect: 'THEATER', name: '극장', cost: 6, text: '역할 선택 종료 후 다른 사람과 역할을 보지 않고 교환할 수 있습니다.' },
  { templateId: 'CB-SP-29', effect: 'THIEVES_DEN', name: '도둑 소굴', cost: 6, text: '건설비 일부 또는 전부를 손패로 지불합니다. 카드 1장당 금화 1개.' },
  { templateId: 'CB-SP-30', effect: 'WISHING_WELL', name: '소원의 우물', cost: 5, text: '종료 시 자신을 포함한 자기 특수 건물마다 +1점.' },
] as const;
export type CitySpecialId = (typeof CITY_SPECIAL_BUILDINGS)[number]['templateId'];
export type CitySpecialEffect = (typeof CITY_SPECIAL_BUILDINGS)[number]['effect'];
export const CITY_STANDARD_CAST: readonly CityJobId[] = ['ASSASSIN','THIEF','MAGICIAN','KING','BISHOP','MERCHANT','ARCHITECT','WARLORD'];
export const CITY_STANDARD_SPECIALS: readonly CitySpecialId[] = ['CB-SP-04','CB-SP-05','CB-SP-09','CB-SP-10','CB-SP-12','CB-SP-13','CB-SP-14','CB-SP-15','CB-SP-22','CB-SP-23','CB-SP-25','CB-SP-27','CB-SP-29','CB-SP-30'];
export type CityExpansionSettings = Readonly<{ enabled: boolean; roles: readonly CityJobId[] }>;
export const CITY_DEFAULT_SETTINGS: CityExpansionSettings = { enabled: false, roles: CITY_STANDARD_CAST };
